### ISSUE TITLE
Issue with spookyhash

### ISSUE THREAD

**Issue by eddelbuettel** [eddelbuettel/digest#105]
spookyhash has now been added, but we are having problems.  Ironically apparently "everywhere" but on the systems @kendonB and I tested on.   

To repeat, run the "check for cran" script from rhub,  _e.g._ via the minimal wrapper [`c4c.r`](https://github.com/eddelbuettel/littler/blob/master/inst/examples/c4c.r)  or directly ` rhub::check_for_cran()`.  It comes back with three out of four failing, including on one basic comparison.

That is, plainly said, not good.   We good either withdraw 'spooky' (sad, given all the work) or mark it as 'highly experimental' and disable tests.  Not my preferred choice.

@kendonB Do you by chance have access to _e.g._ Windows so that you could see why the test fails there?  The other Linux fail coming back from `rhub` may be related.

**Comment by kendonB** [comment]
I think it's the new tests I introduced to increase coverage. I think I can fix.

**Comment by eddelbuettel** [comment]
Ok, as a general rule  I would also prefer it if we could discuss what you plan to change _before_ you throw it over the fence as a PR.  As we learned anyway, Travis, while helpful for some things, does not catch everything.

Could you possibly run `rhub::check_for_cran()` and report back how many of the four it now passes?    And, to be plain, the UBSAN/ASAN failure is way more important than coverage numbers.   It took concerted effort and help from several folks to get us "clean" for those reports, I really would not like to revert back to having an offence noted there.

**Comment by kendonB** [comment]
The tests weren't wrong, the code was. In `digest.R`, `skip="auto"` wasn't getting turned into into `skip=14`. 

These changes work:
https://github.com/eddelbuettel/digest/compare/master...kendonB:spooky_patch_1?expand=1

Now the code only skips serialization for the streaming_algos but processes the `skip` argument the same as other algos.

OK for PR? Do you know of a way for me to use `covr` to test coverage against your copy of `digest`? 

I get 3 passes and a note on Ubuntu:
```
* checking compilation flags used ... NOTE
Compilation used the following non-portable flag(s):
  ‘-Wdate-time’ ‘-Werror=format-security’ ‘-Wformat’
```

**Comment by eddelbuettel** [comment]
Nice. That sounds like the right fix.

And even ASAN passes? 

Also, the `‘-Wdate-time’ ‘-Werror=format-security’ ‘-Wformat’` you can ignore; I just fixed that "upstream" in the R Debian package.  More details are on the `r-sig-debian` list and in a few places online including just this weekend on r-package-devel.  In a nutshell we just add this to the bottom of Renviron.site:  

```sh
## edd May 2019
##
## Debian (and its derivatives) impose a set of compiler flags to prevent some known
## security issues with compiled code.  These flags then become defaults for R as well
## (see eg /etc/R/Makeconf) but nevertheless confuse R as warnings get triggers.  Users,
## on the other hand, are often stumped about these.  So with this variable we declare
## these options as known for the local checks on the machine this file is on.
##
## See Section 8 of the R Internals manual for many more options to customize tests.
_R_CHECK_COMPILATION_FLAGS_KNOWN_='-Wformat -Werror=format-security -Wdate-time'
```

**Comment by eddelbuettel** [comment]
> OK for PR? 

I'd say so.  It would be nice if you could also update `ChangeLog`.

> Do you know of a way for me to use covr to test coverage against your copy of digest?

Install the `covr` package and run `res <- covr::codecov()` just like the travis run does. I have forgotten the details but I think you can viz locally.  It think there is a shiny viewer in package or something,

**Comment by kendonB** [comment]
May not get to this for a few days, FYI

**Comment by eddelbuettel** [comment]
Not to worry.  Also, don't obsess over coverage. That is easy to fudge.

Tests should pass on all platforms.  That is important.   Slighly less important but still 'up there' is not triggering UBSAN.  I did in the meantime submit the CRAN release version and it passes fine on that rhub test as well (there was some concern that that instance always reports FAIL I wanted to double check, does not seem to generate false positives).  

This good stuff, but we need to do it right.  "No shortcuts" as they say.

**Comment by cgonza12** [comment]
I've upgraded to the latest R version for Mac and can no longer install the "digest" package. Could this issue be the reason why?

When I try to install I get this error:
```
clang: warning: no such sysroot directory: '/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk' [-Wmissing-sysroot]
SpookyV2.cpp:14:10: fatal error: 'memory.h' file not found
```

Session info
```
R version 3.6.0 (2019-04-26)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.6

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

Random number generation:
 RNG:     Mersenne-Twister 
 Normal:  Inversion 
 Sample:  Rounding 
 
locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] ggplot2_3.1.1

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.1       rstudioapi_0.10  munsell_0.5.0    colorspace_1.4-1 R6_2.4.0         rlang_0.3.4      plyr_1.8.4       tools_3.6.0     
 [9] grid_3.6.0       gtable_0.3.0     cli_1.1.0        withr_2.1.2      rprojroot_1.3-2  lazyeval_0.2.2   assertthat_0.2.1 tibble_2.1.1    
[17] crayon_1.3.4     processx_3.3.1   callr_3.2.0      ps_1.3.0         compiler_3.6.0   pillar_1.4.0     backports_1.1.4  desc_1.2.0      
[25] scales_1.0.0     pkgconfig_2.0.2 
```

**Comment by eddelbuettel** [comment]
Hm, that is a very default header. Check the macOS / R tutorials for setting up a development environment, or rely on the prebuilt `digest` off CRAN.

**Comment by eddelbuettel** [comment]
And I checked it just fine on the macOS build of rhub.  You can see the status and logs for the next little while here:  https://builder.r-hub.io/status/digest_0.6.19.tar.gz-763db0dbaa584c79b9391f14e16a4772

Build artifacts will be here:   https://artifacts.r-hub.io/digest_0.6.19.tar.gz-763db0dbaa584c79b9391f14e16a4772

**Comment by eddelbuettel** [comment]
We can close this one too with version 0.6.19 on CRAN.
