### ISSUE TITLE
Shared Object digest.so Not Found

### ISSUE THREAD

**Issue by jdonnell01** [eddelbuettel/digest#114]
I am attempting to deploy an R Shiny application via Docker using the R-Base image (https://hub.docker.com/r/openanalytics/r-base). When I execute the shiny::runapp command I am presented with the below error:

_Error in library.dynam(lib, package, package.lib): shared object digest.so not found_

**My sessionInfo:**
R version 3.5.2 (2018-12-20)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.1 LTS

Matrix products: default
BLAS: /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

loaded via a namespace (and not attached):
[1] compiler_3.5.2

**Comment by eddelbuettel** [comment]
Please talk to our friends at OpenAnalytics -- the `digest` simply works.

**Comment by eddelbuettel** [comment]
Lastly, it being Ubuntu you could _either_ have a binary `r-cran-digest` installed from the system, _or_ have `digest` installed from CRAN.  You didn't say which.

But in general, you have not demonstrated a shortcoming in `digest`.  You seem to be experiencing a failure in something _relying on `digest`_.

**Comment by jdonnell01** [comment]
Thank you - I appreciate the quick response. This being run on Ubuntu would you suggest that I leverage the r-cran-digest binary rather than the digest package from CRAN? (the CRAN version is what I am using now)

**Comment by eddelbuettel** [comment]
That is up to you, a big topic I have been explaining many times in the 15+ years I have looked after either some of those `r-cran-*` or binaries myself.

But none of that has anything to do with the `digest` package, and I hope you do not mind me closing this.  

The `r-sig-debian` mailing list is good for such broader questions.  Maybe try it, and it archives. (You need to subscribe to post.)

**Comment by jdonnell01** [comment]
OK, thank you. I ran `tinytest::test_package('digest')` in my environment and I received the error:

_Error: package digest was built for x86_64-w64-mingw32_

I am running x86_64-pc-linux-gnu (64-bit). Is there a Linux version of the digest package?

**Comment by eddelbuettel** [comment]
Yes.  

```sh
edd@rob:~$ apt-cache search r-cran-digest
r-cran-digest - GNU R package for 'hash digest' of R data structures
edd@rob:~$
```
