### ISSUE TITLE
CFB cipher implementation 

### ISSUE THREAD

**Issue by isuruceanu** [eddelbuettel/digest#118]
Is there any plan to support [Cipher Feedback (CFB)](https://en.wikipedia.org/wiki/Block_cipher_mode_of_operation#Cipher_Block_Chaining_(CBC))?

**Comment by eddelbuettel** [comment]
Not yet.  We could have you an implementation with a compatible / suitable license, and maybe also test functions and/or input and output.  We have extended the package in the past to other ciphers via suitable PRs.  Do you want to work on this?

I only glanced at the linkL what does CFB do for you?  Do you use it another context? Or speed?

**Comment by isuruceanu** [comment]
We have an app written in golang which collect some data and encrypt it using aes.CFB cipher. We want to analyze and use it for some ML, because of luck good ML packages in golang we are looking to use python or R. Python has an implementation of CFB cipher which is fine, just looking for R package too.

Will try to implement it, although haven't done any c/c++ for along time :)

**Comment by eddelbuettel** [comment]
Sounds good.  It _should_ be straightforward as we (generally) just take a `char*` in (with the already serialized R object) and return one with the digest.  Poke us here if you have questions.  Several of the existing digests should providing working examples.
