### ISSUE TITLE
sha1() fails on Inf

### ISSUE THREAD

**Issue by billdenney** [eddelbuettel/digest#120]
When running `sha1()` on `Inf`, an error occurs.

``` r
library(digest)
sha1(Inf)
#> Warning in num2hex(x, digits = digits, zapsmall = zapsmall): NAs introduced
#> by coercion to integer range
#> Error in if (any(zero)) {: missing value where TRUE/FALSE needed
```

<sup>Created on 2019-10-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by eddelbuettel** [comment]
Confirmed.  `sha1.numeric` calls `digest:::num2hex` which fails.  Hm.

@ThierryO Any idea how to work a fix in?

**Comment by billdenney** [comment]
I'm almost done with a PR right now that at least works (hopefully it matches the desired method).

**Comment by eddelbuettel** [comment]
Nice!  I had seen that you forked it.  And using `is.finite()` is good.  And you win the prize for most complete with ChangeLog _and_ tests!  Looks good. Once you open maybe also flag @ThierryO for a review as courtesy.

**Comment by billdenney** [comment]
@eddelbuettel, When I'm able, I try to be a good neighbor.  :)

I'm not sure what you mean by "Once you open maybe also flag @ThierryO for a review as courtesy."  Flag him in the PR?

**Comment by eddelbuettel** [comment]
When I wrote that I was unaware that you already had / or were concurrently opening the PR.  Just how you tagged me for a review, could you tag him?   (GitHub is little mysterious to me here about who usually ends up in that selected box.  But past committers should work.  If it does't, no mas.)

(And I need a coffee.  I just wrote the above as a comment/edit in your last post.  Gee.  Fixed now.)

**Comment by billdenney** [comment]
The mystery of GitHub appeared to automatically tag you for review-- I didn't do anything.  But, I'll drop a bump for him in the PR.
