### ISSUE TITLE
Generalization of sha1.default

### ISSUE THREAD

**Issue by billdenney** [eddelbuettel/digest#125]
As I was trying to improve the `sha1` for the PKNCA package, I found that I needed `sha1.sessionInfo()` and `sha1.packageDescription()` functions.  Those would be just be:

```r
sha1.sessionInfo <- digest:::sha1.list
sha1.packageDescription <- digest:::sha1.list
```

That made me think that a generalization of the `sha1.default()` function to check with something like the following would help:

```r
if (is.list(x)) {
  sha1.list(x=x, digits = digits, zapsmall = zapsmall, ..., algo = algo)
} else {
  # The current stop message
}
```

And, the one other change that may be of interest would be that `sha1.list()` pull out the attributes of the list for checking, too.  (Though, that looks like a different issue that I'll open separately.)

https://github.com/eddelbuettel/digest/blob/4c415fe2b67b760f7cd64767620d561a5a1a0ed6/R/sha1.R#L28-L35

Would such a PR be of interest, or would you prefer the specific methods for each class?  (And therefore you would prefer a PR that explicitly names the sessionInfo and packageDescription classes.)

Tag: @ThierryO, @eddelbuettel

**Comment by eddelbuettel** [comment]
From the top of my head:  thumbs-up.   Looks like a clean extension not really altering interfaces (well, `sha1.list()` will not croak as often) and extending it in a useful way.  

But I don't use sha1 much eager to hear what @ThierryO may say...

**Comment by ThierryO** [comment]
Seems like a good idea. I'd write it as

```
if (is.list(x)) {
  return(sha1.list(x=x, digits = digits, zapsmall = zapsmall, ..., algo = algo))
}
# The current stop message
```
