### ISSUE TITLE
Code Simplification

### ISSUE THREAD

**Issue by billdenney** [eddelbuettel/digest#130]
As I've been looking a lot at the code for `sha1()` over the past few weeks, I realized that there is some duplication there that could be simplified.  I did a programmatic look over the functions in the package, and I found that the following are all identical functions:

* "sha1.call" "sha1.character" "sha1.factor"    "sha1.integer"   "sha1.logical"   "sha1.raw"      
* "sha1.name" "sha1.NULL"

Would you be interested in a PR that combines these together into two functions (named something like `sha1_attr_digest()` and `sha1_digest()`) which would cover the general cases and then have a simple assignment so that all of these classes are covered?  (To make this more concrete, I would rename the `sha1.call()` function to `sha1_attr_digest()` then make an assignment of `sha1.call <- sha1.character <- sha1.factor <- sha1.integer <- sha1.logical <- sha1.raw <- sha1_attr_digest`.  (And similar with `sha1.name()` becoming `sha1_digest()` and assigning `sha1.name <- sha1.NULL <- sha1_digest`.)

The benefit that I see is that there are fewer lines of code (removing repetition), future classes that can follow one of these two paradigms could simply be added by an additional assignment, and if a structural change were made in the future, it would require fewer changes to ensure consistency.

(An underlying goal with this is a "thank you PR" for your support in my recent requests!)

Code to find this was:

```r
library(digest)

all_funs <- unclass(lsf.str(envir = asNamespace("digest"), all.names = TRUE))

remaining_funs <- all_funs
identical_funs <- list()
idx1 <- 1
while (idx1 < length(remaining_funs)) {
  idx2 <- idx1 + 1
  while (idx2 <= length(remaining_funs)) {
    if (identical(x=get(x=remaining_funs[idx1], envir=asNamespace("digest")),
                  y=get(x=remaining_funs[idx2], envir=asNamespace("digest")))) {
      identical_funs[[remaining_funs[idx1]]] <-
        c(identical_funs[[remaining_funs[idx1]]], remaining_funs[idx2])
      remaining_funs <- remaining_funs[-idx2]
    } else {
      idx2 <- idx2 + 1
    }
  }
  idx1 <- idx1 + 1
}
identical_funs
```

**Comment by eddelbuettel** [comment]
@ThierryO That's mostly your stomping grounds.  Thoughts?

**Comment by ThierryO** [comment]
This seems a good idea. I'd rather do it as
```
sha1.character <- fucntion(...) { sha1_attr_digest(...)}
sha1.factor <- fucntion(...) { sha1_attr_digest(...)}
```

because `sha1.character <- sha1_attr_digest` is missed by the code coverage checks. And we want to make sure to have a unit test for each class.

**Comment by billdenney** [comment]
I understand that goal well.  As you can see with the reference above this comment, I've asked if this is something that is reasonable to change in `covr` (though I will fully understand if it isn't).  Depending on your answer to the question below, I'll wait for that answer to play out before making this modification.  (I'd like the `covr` modification for reasons beyond this specific issue.)

@ThierryO, if `covr` is modified, do you prefer the code that I originally suggested or your code?  Also, would you want the `sha1_digest()` and `sha1_attr_digest()` functions exported?  (I would think yes to export so that other packages could use them very simply and have them clearer in their code, but I'd like to confirm.)

**Comment by eddelbuettel** [comment]
Please explain what you mean by "`covr` modified".  I never needed that.  Did you maybe just mean "add `#noco` tags" ?

**Comment by billdenney** [comment]
I mean that if `covr` has a feature update where it will indicate coverage on lines that are only function assignment (like `sha1.character <- sha1_attr_digest`, as suggested in r-lib/covr#245), would that style be preferred?  I did not want to suggest adding `#nocov` as that would prevent the goal of ensuring coverage for all classes.

**Comment by ThierryO** [comment]
I don't mind the style `sha1.character <- sha1_attr_digest`. It is shorter and more elegant than my workaround. However I find a good code coverage check more important than the most elegant code.

I suggest to wait and see what the reactions are on  r-lib/covr#245.

**Comment by eddelbuettel** [comment]
@billdenney Gotcha.  Yes, `#nocov` is cheating.  Another day ... ;-)

Whatever you two prefer stylistically, I would prefer to not depend on particular version of external tools.

**Comment by ThierryO** [comment]
`#nocov` is only for when it is hard to a write a good unit test. In this case we a) have unit tests and b) want to test the functionality for each class.

The current version of `covr` does not detect the `sha1.character <- sha1_attr_digest` constructs. IMHO we should not use these constructs as long as `covr` can't handled them. I would only use them when the CRAN version on `covr` handles them. Hence my suggestion to wait and see what happens with `covr`.

**Comment by eddelbuettel** [comment]
Fair enough.  We can also make some (simple) changes now and then some more in a few months time.
