### ISSUE TITLE
Improve sha1 efficiency

### ISSUE THREAD

**Issue by billdenney** [eddelbuettel/digest#133]
Probably a question for @ThierryO.

I needed to generate a hash on a data.frame with about 1M rows and about 5 numeric columns (so, about 5M total numeric values), and it took a bit of time (many seconds).  So, I was looking for where I could help make things faster, and the answer appears to come in `num2hex()`.

At a first look, most of the time is spent in various forms of string manipulation, and as I dove down the rabbit hole of trying to make those string manipulations faster, I found the C++ function `frexp` which extracts the mantissa and exponent.  I wonder if we could substitute most of the more time-intensive string manipulation in `num2hex()` with a simpler C++ call to `frexp` (and then also do the hex generation there, too, using the integer form)?

**Comment by eddelbuettel** [comment]
From a quick glance at Google this seems to be a well-travelled area. Not sure we can pick up much.

One link:  https://crypto.stackexchange.com/questions/60346/fastest-way-to-compute-iterates-of-sha1

**Comment by billdenney** [comment]
Thanks for that research.  While my goal is general, at least in this first case for num2hex, I’m working on the steps before the actual hash calculation.  In my quick profiling of larger numeric vectors, over 90% of the time is spent in sprintf and gsub to extract the negative sign, mantissa, and exponent.  I’m wanting to make that part more efficient as the first step.

**Comment by billdenney** [comment]
A second way to consider this issue is a general request to look for efficiency improvements.  The package works well, and it appears to be generally stable and feature-complete, so trying for more efficiency seems reasonable to me.  (Selfishly says the guy who is using it for operations taking many seconds to minutes...)

**Comment by eddelbuettel** [comment]
Poor man's efficiency is just throwing it at a bazillions cores :)

**Comment by billdenney** [comment]
Ahh, to be so poor!  :)

**Comment by billdenney** [comment]
I think that the `num2hex()` update is what I have a reasonable chance of finding.  I'm going to close this.
