### ISSUE TITLE
sha1 tests fragility under r-devel on linux

### ISSUE THREAD

**Issue by eddelbuettel** [eddelbuettel/digest#136]
@billdenney @ThierryO 
I have a pending upload to CRAN but had to take out the tests deactivated in this commit:  https://github.com/eddelbuettel/digest/commit/ab60ab3c87e50a374b00376829fc8b488925bbf4

I was unable to confirm the failure here even though I have a current r-devel.  We will need to take another look.  It _may_ have to do with the changed treatment of matrices with respect to arrays, but that is just a guess...

**Comment by billdenney** [comment]
I don't track r-devel closely as most of my work is relatively R version-independent.

With a quick look, I thin that you're correct for at least some of the tests.  the class for matrix objects will be `c("matrix", "array")` in 4.0.0 and future, so I think that at least some of the fixes may be:

Change:
https://github.com/eddelbuettel/digest/blob/ab60ab3c87e50a374b00376829fc8b488925bbf4/inst/tinytest/test_sha1.R#L99

to

`class = class(x.matrix.num)`

and change:

https://github.com/eddelbuettel/digest/blob/ab60ab3c87e50a374b00376829fc8b488925bbf4/inst/tinytest/test_sha1.R#L113

to

`class = class(x.matrix.letter)`

This line also has the same issue (though I think that the solution would be to precompute the hash for that matrix):
https://github.com/eddelbuettel/digest/blob/ab60ab3c87e50a374b00376829fc8b488925bbf4/inst/tinytest/test_sha1.R#L438

The other issues are less clear to me.

**Comment by eddelbuettel** [comment]
Ok, I actually (just) had an r-devel version new enough but I did _not_ have the required environment variable set.  Once I set it the tests do fail for me.  I am not quite sure what the best course of action is but we can revisit this over the next few weeks -- no rush.

**Comment by ThierryO** [comment]
My [git2rdata](https://github.com/ropensci/git2rdata) uses Travis to run checks on R release, oldrel and devel under Linux and release under OSx. Shall I send a PR to do this for digest too?

**Comment by eddelbuettel** [comment]
Thanks for offering but I am very happy with the current Travis setup. It does what it does on purpose, and I maintain it over here: https://eddelbuettel.github.io/r-travis/  I have no issue running r-devel, the comment above was just a (very brief) follow-up explaining why my very first attempt at replicating failed.  It needed r-devel new enough (which I had) _and_ setting an env var (which I had not),

**Comment by ThierryO** [comment]
This seems to be not only related to r-devel. I get different sha1 hashes between digest 0.6.22 and 0.6.23 with R 3.6.0 running Ubuntu 18.04

**Comment by eddelbuettel** [comment]
Do you have a concrete / reproducible example?  We should look into this.

FWIW we look good at CRAN https://cloud.r-project.org/web/checks/check_results_digest.html with the one outlier being caused by them (new rtools setup seems incomplete).

**Comment by ThierryO** [comment]
Stupid me. f5a8b39 changes the way hashes are calculated. I calculated hashes in 0.6.23 and then checked them using and older version. And those are different by design. So this was a false alarm, unfortunately.

**Comment by eddelbuettel** [comment]
All good, and the issue above _was_ also reproduced with r-devel and the proper environment variable.

**Comment by eddelbuettel** [comment]
This was close with the merge in December, thanks again @ThierryO
