### ISSUE TITLE
Faster alternative to Sys.info() in digest()

### ISSUE THREAD

**Issue by wlandau** [eddelbuettel/digest#137]
I develop packages that call `digest()` repeatedly on small data. For use cases like these, the time spent on `Sys.info()` is often noticeable.

```r
library(digest)
library(fs)
library(profile)
library(withr)

profile <- function(plan) {
  local_dir(dir_create(tempfile()))
  replicate(1e4, digest(letters, algo = "murmur32"))
  rprof <- "prof.rprof"
  pprof <- "prof.pprof"
  Rprof(filename = rprof)
  replicate(1e4, digest(letters, algo = "murmur32"))
  Rprof(NULL)
  data <- read_rprof(rprof)
  write_pprof(data, pprof)
  vis_pprof(pprof)
}

vis_pprof <- function(path, host = "localhost", port = NULL) {
  server <- sprintf("%s:%s", host, port %||% random_port())
  message("local pprof server: http://", server)
  args <- c("-http", server, path)
  if (on_windows()) {
    shell(paste(c("pprof", args), collapse = " "))
  } else {
    system2(jointprof::find_pprof(), args)
  }
}

random_port <- function(from = 49152L, to = 65355L) {
  sample(seq.int(from = from, to = to, by = 1L), size = 1L)
}

on_windows <- function() {
  tolower(Sys.info()["sysname"]) == "windows"
}

`%||%` <- function(x, y) {
  if (is.null(x) || length(x) <= 0) {
    y
  } else {
    x
  }
}

profile()
```

![windows](https://user-images.githubusercontent.com/1580860/70101023-a78c7580-1601-11ea-9837-ba90fe78562a.PNG)

Instead of

https://github.com/eddelbuettel/digest/blob/fe990a397700df45884c94dddb17729d05b970e9/R/digest.R#L41

would you be open to this?

```r
isWindows <- .Platform$OS.type == "windows"
```

It looks much faster.

```r
> microbenchmark::microbenchmark(a = .Platform$OS.type, b = Sys.info()[["sysname"]])
Unit: nanoseconds
 expr   min    lq  mean median    uq    max neval
    a   100   150   530    300   900   2900   100
    b 46700 49500 59365  50500 63250 168600   100
```

I would have just submitted a PR, but I need to jump through a couple hoops at my company first.

**Comment by eddelbuettel** [comment]
Good for the hoops :)   I prefer talking before blindly jumping into PR.

What you suggest sounds fine.  Givem that the platform one runs on rarely changes, we could also check once and only once at load, and the just retrieve a bool from a per-package env.  Even cheaper?  Worth it?  Or not?

**Comment by eddelbuettel** [comment]
Also, instead of

```r
isWindows <- .Platform$OS.type
```

presumably a _comparison_ of that value against a known truth, no?

**Comment by wlandau** [comment]
> presumably a comparison of that value against a known truth, no?

Yes. I just fixed the typo.

**Comment by wlandau** [comment]
> What you suggest sounds fine. Givem that the platform one runs on rarely changes, we could also check once and only once at load, and the just retrieve a bool from a per-package env. Even cheaper? Worth it? Or not?

I like that idea. The speedup might be small compared to the rest of `digest()`, but per-package envs are straightforward to implement.

``` r
library(digest)
library(microbenchmark)
env <- new.env(parent = emptyenv())
env$is_windows <- TRUE
microbenchmark(
  env = env$is_windows,
  cmp = .Platform$OS.type == "windows",
  digest = digest(NULL)
)
#> Unit: nanoseconds
#>    expr   min    lq     mean  median      uq    max neval
#>     env   167   186   335.86   285.0   475.5   1377   100
#>     cmp   275   305   578.61   542.0   790.5   4228   100
#>  digest 69038 69970 75483.77 70550.5 71198.5 476413   100
```

<sup>Created on 2019-12-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by eddelbuettel** [comment]
Yes. I have been using for many years; `rpushbullet` comes to mind, probably others too.  I can take care of it, or if feel like it, can welcome a PR.

**Comment by wlandau** [comment]
Thanks, Dirk. Since you are willing, I will leave the implementation to you. If you change your mind, please let me know and I will submit a PR.

**Comment by eddelbuettel** [comment]
I'll put it in a branch and let you review / test.  Cool?

**Comment by wlandau** [comment]
Sounds great.
