### ISSUE TITLE
Faster alternative to match.arg() in digest()

### ISSUE THREAD

**Issue by wlandau** [eddelbuettel/digest#139]
As with `Sys.info()` in #137, `digest()` spends a noticeable amount of time on `match.arg()` (see the flame graphs in #138). Would it be reasonable to explore cheaper alternatives to partial argument matching for `algo` and `errormode`?

**Comment by eddelbuettel** [comment]
:man_shrugging: 

Hard to tell if it matters or if we go off into obscure territory.  It _is_ a base R function so there is probably not that much fluff.  

Also note that we now have a vectorized caller -- so maybe look into `getVDigest()`?   And or if you're so pressed for time maybe call `.Call(digest_impl)` directly with properly set up arguments?

**Comment by wlandau** [comment]
> Also note that we now have a vectorized caller -- so maybe look into getVDigest()? And or if you're so pressed for time maybe call .Call(digest_impl) directly with properly set up arguments?

I will look into it, thanks.

**Comment by wlandau** [comment]
`getVDigest()` circumvents this exact problem!

```r
library(digest)
library(fs)
library(profile)
library(withr)

profile <- function(plan) {
  local_dir(dir_create(tempfile()))
  f <- getVDigest(algo = "murmur32")
  replicate(1e4, f(letters)) # warmup
  start <- proc.time()
  replicate(1e4, f(letters))
  print(proc.time() - start)
  rprof <- "prof.rprof"
  pprof <- "prof.pprof"
  Rprof(filename = rprof)
  replicate(1e4, f(letters))
  Rprof(NULL)
  data <- read_rprof(rprof)
  write_pprof(data, pprof)
  vis_pprof(pprof)
}

vis_pprof <- function(path, host = "localhost", port = NULL) {
  server <- sprintf("%s:%s", host, port %||% random_port())
  message("local pprof server: http://", server)
  args <- c("-http", server, path)
  if (on_windows()) {
    shell(paste(c("pprof", args), collapse = " "))
  } else {
    system2(jointprof::find_pprof(), args)
  }
}

random_port <- function(from = 49152L, to = 65355L) {
  sample(seq.int(from = from, to = to, by = 1L), size = 1L)
}

on_windows <- function() {
  tolower(Sys.info()["sysname"]) == "windows"
}

`%||%` <- function(x, y) {
  if (is.null(x) || length(x) <= 0) {
    y
  } else {
    x
  }
}

profile()
```

![vec](https://user-images.githubusercontent.com/1580860/70188150-f992d100-16bd-11ea-948d-8c602d1652b6.PNG)

**Comment by eddelbuettel** [comment]
Yay!
