### ISSUE TITLE
Overhead in `digest()` due to `::`

### ISSUE THREAD

**Issue by wlandau** [eddelbuettel/digest#140]
As with `Sys.info()` in #137 and `match.arg()` in #139, `digest()` spends a noticeable amount of time on `::` (#138). How do you feel about using `serialze()` instead of `base::serialize()` if it removes this overhead?

**Comment by eddelbuettel** [comment]
Dear Will.  Can we now stop piling new issues up here?  This is *fundamentally* all the same as #137, no?

**Comment by eddelbuettel** [comment]
And what is `serialze()` ?

This package existed since R 1.8.0 brought us `base::serialize()`.  Relying on base R to serialize any odd R object has served us reasonably well.

**Comment by wlandau** [comment]
> Dear Will. Can we now stop piling new issues up here? This is fundamentally all the same as #137, no?

Sure, sorry that was bothersome.

> And what is serialze()?

> This package existed since R 1.8.0 brought us base::serialize(). Relying on base R to serialize any odd R object has served us reasonably well.

Yes, I agree with using serialization from `base`. I just wondering about the (admittedly slight) cost of explicitly writing `base::`. `::` and `getExportedValue()` tend to appear in my profiling studies.

**Comment by eddelbuettel** [comment]
There must have been a reason at some point why I explicitly prefixed it.  Maybe it was this:

```
2004-05-26  Dirk Eddelbuettel  <edd@debian.org>

        * Release 0.1.2
        - R/zzz.R: remove test for R < 1.8.0 and load of serialize package
          (as serialize has been removed from CRAN with serialize() in R)

```

**Comment by wlandau** [comment]
Interesting, I did not know there was a `serialize` package originally. I see no danger of ambiguity now.

Perhaps I was excessive when I opened an issue about prefixing in `digest()`. However, I do think it could be an easy win for functions produced by `getVDigest()`. (By the way, thanks again for the tip in #139! It is already speeding up `drake`: https://github.com/ropensci/drake/issues/1092.)

```r
library(digest)
library(fs)
library(profile)
library(withr)

inner_digest <- getVDigest(algo = "murmur32")
digest_murmur32 <- function(object, serialize = TRUE, ...) {
  if (serialize) {
    inner_digest(list(object), serialize = TRUE, ...)
  } else {
    inner_digest(object, serialize = FALSE, ...)
  }
}

profile <- function(plan) {
  local_dir(dir_create(tempfile()))
  replicate(1e5, digest_murmur32(letters))
  rprof <- "prof.rprof"
  pprof <- "prof.pprof"
  Rprof(filename = rprof)
  replicate(1e5, digest_murmur32(letters))
  Rprof(NULL)
  data <- read_rprof(rprof)
  write_pprof(data, pprof)
  vis_pprof(pprof)
}

vis_pprof <- function(path, host = "localhost", port = NULL) {
  server <- sprintf("%s:%s", host, port %||% random_port())
  message("local pprof server: http://", server)
  args <- c("-http", server, path)
  if (on_windows()) {
    shell(paste(c("pprof", args), collapse = " "))
  } else {
    system2(jointprof::find_pprof(), args)
  }
}

random_port <- function(from = 49152L, to = 65355L) {
  sample(seq.int(from = from, to = to, by = 1L), size = 1L)
}

on_windows <- function() {
  tolower(Sys.info()["sysname"]) == "windows"
}

`%||%` <- function(x, y) {
  if (is.null(x) || length(x) <= 0) {
    y
  } else {
    x
  }
}

profile()
```

![Screenshot_20191204_235759](https://user-images.githubusercontent.com/1580860/70205545-590ad400-16f2-11ea-9c8c-e9453dac1a83.png)

![Screenshot_20191205_000227](https://user-images.githubusercontent.com/1580860/70205595-88b9dc00-16f2-11ea-9c85-e4395f6d37b9.png)

Looks like we could cut runtime in half just by removing "base::" here:

https://github.com/eddelbuettel/digest/blob/7d60b5b7388f9a2e003812609246314fea22c75d/R/vdigest.R#L54

https://github.com/eddelbuettel/digest/blob/7d60b5b7388f9a2e003812609246314fea22c75d/R/vdigest.R#L173-L174

and maybe sweep up a couple breadcrumbs if we put `names(formals(serialize))` in `.pkgenv`.

https://github.com/eddelbuettel/digest/blob/f71e40585ee80beb5808cfb5e278b553e7053034/R/vdigest.R#L54

**Comment by eddelbuettel** [comment]
I just ran a simple comparison against an alternate build where I did `s/base::serialize/serialize/`.  The difference (in a simple test of 100 `replicate` calls to digest on a large and boring integer vector) was minimal:  1.37 sec versus 1.45 sec.  I understand you want `drake` to be lightweight and all that, but it is a workflow manager used for large and long-running projects.   This, for the sake of code clarity and defensiveness, is not a screw I want to turn.  I hope you understand.

**Comment by wlandau** [comment]
I do understand, thanks for looking into it. Functions from `getVDigest()` are already super fast.

**Comment by eddelbuettel** [comment]
One super low-hanging fruit is the test for 'sharing' which we could move to the already-existing `init.R` and a toggle in the environment.  It would help for repeated calls.  But, as the package after almost 20 now has proper vectorised call support, it may not be as urgent as it was.

**Comment by wlandau** [comment]
I think we do see a little more speed due to https://github.com/eddelbuettel/digest/issues/140#issuecomment-562138505. Would you like me to submit a PR? I have permission now, and I think the code is ready for review.

```r
# 7d60b5b7388f9a2e003812609246314fea22c75d (eddelbuettel/digest@master)
library(digest)
system.time(replicate(1e5, digest("abc", algo = "murmur32")))
#>   user  system elapsed 
#>  3.495   0.010   3.505 
vdigest <- getVDigest(algo = "murmur32")
system.time(replicate(1e5, vdigest("abc")))
#>   user  system elapsed 
#>  2.223   0.010   2.234 
```

```r
# 465e885cfa2bdc980921ad455605a49e61dac349 (wlandau/digest@sharing)
library(digest)
system.time(replicate(1e5, digest("abc", algo = "murmur32")))
#>   user  system elapsed
#>  3.068   0.006   3.097
vdigest <- getVDigest(algo = "murmur32")
system.time(replicate(1e5, vdigest("abc")))
#>   user  system elapsed
#>  1.672   0.000   1.673
```

```r
> sessionInfo()
R version 3.6.1 (2019-07-05)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.3 LTS

Matrix products: default
BLAS:   /home/landau/R/R-3.6.1/lib/libRblas.so
LAPACK: /home/landau/R/R-3.6.1/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8      
 [2] LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8       
 [4] LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8   
 [6] LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8      
 [8] LC_NAME=C                 
 [9] LC_ADDRESS=C              
[10] LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8
[12] LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils    
[5] datasets  methods   base     

other attached packages:
[1] digest_0.6.23

loaded via a namespace (and not attached):
[1] compiler_3.6.1 tools_3.6.1    yaml_2.2.0  
```

**Comment by eddelbuettel** [comment]
I am sorry but I am having some cognitive difficulties with your 100 line posted mcve.  Life is just too short for a full article in each post.  

Could you actually say what you are proposing in a bullet point or two?

**Comment by wlandau** [comment]
- I propose we pre-compute the value of `"nosharing" %in% names(formals(base::serialize))` and use the result in `digest` functions (your idea from https://github.com/eddelbuettel/digest/issues/140#issuecomment-562138505).
- I implemented this in https://github.com/wlandau/digest/commit/465e885cfa2bdc980921ad455605a49e61dac349. On my machine, it seems to make `digest()` about 12% faster and functions from `getVDigest()` about 25% faster for repeated calls on small data.

**Comment by eddelbuettel** [comment]
That was more comprehensible and compact.  In favor.  

Please try to follow what we do around here i.e. ideally add a ChangeLog entry (and this package is so old old it newer got NEWS.Rd so it is just ChangeLog).

**Comment by eddelbuettel** [comment]
(And not to leave it unsaid: as an empirically-minded person I *do* like your aggressive profiling for gains.  That is the right approach!)

**Comment by wlandau** [comment]
Thanks, Dirk! I just prepended an entry to `ChangeLog`.
