### ISSUE TITLE
Feature request: Optionally return NA instead of throwing an error

### ISSUE THREAD

**Issue by krlmlr** [eddelbuettel/digest#15]
Rationale: Avoiding `tryCatch` for callers that are aware that `digest()` might fail. As discussed hadley/testthat#299.

Interface: Something along the lines of

```
digest(..., error = c("fail", "warn", "silent"))
```

**Comment by eddelbuettel** [comment]
Looking at this now and liking it less and less.  `error()` occurs essentially only if the file cannot be opened --> caller's fault --> should be handled by caller.

**Comment by eddelbuettel** [comment]
Ok, in https://github.com/eddelbuettel/digest/commit/3a82b1017a627f433fc770922c740066cb39aa14 things are not too bad.  Take a look if you can live with that.

**Comment by krlmlr** [comment]
Thanks for looking into it. I think a combination of errormode "warn" with checks for file existence will do the trick in testthat.
