### ISSUE TITLE
Cannot install on Macos-latest / R-devel in github actions

### ISSUE THREAD

**Issue by lrnv** [eddelbuettel/digest#152]
Hi, 

It seem that for a few weeks now, the digest package fails to install on mac-os latest runner from github-actions using R-devel. See for exemple the log of one of my packages [there](https://github.com/lrnv/cort/runs/629102326). 

The log looks like : 

```
* installing *source* package ‘digest’ ...
** package ‘digest’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
ccache /usr/local/clang8/bin/clang++ -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/usr/local/include   -fPIC  -Wall -g -O2  -c SpookyV2.cpp -o SpookyV2.o
SpookyV2.cpp:14:10: fatal error: 'memory.h' file not found
#include <memory.h>
         ^~~~~~~~~~
1 error generated.
make: *** [SpookyV2.o] Error 1
ERROR: compilation failed for package ‘digest’
```
Is this a known issue ? A `digest`-related one or a R-devel related one ? Or something i did wrong on my side (entierly possible ;) ).

**Comment by eddelbuettel** [comment]
I suggest you ask on r-sig-mac and/or where the GH actions are supported.  It clearly not an issue on systems that are correctly set up, including macOS, as the CRAN results page shows:
https://cloud.r-project.org/web/checks/check_results_digest.html

Moreover, `memory.h` is about as core a C header as it gets.  Your environment is simply not set up right, but I don't use macOS so I can't help you make it right.

**Comment by lrnv** [comment]
Thanks for the insight !

**Comment by eddelbuettel** [comment]
_De nada_.  I am truly sorry that macOS is so developer-unfriendly.  If I got a penny for each "bug report" due to simply borked setups on macOS I'd retire rich and soon. Almost at least.

**Comment by lrnv** [comment]
Hahaha. Sadly, some of my users are on mac :/
