### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by hildebs42** [eddelbuettel/digest#157]
Hello, I am relatively new to R and I am having issues installing digest as a dependency for another package. I even tried to install directly, and I get the following error in both cases:

> install.packages('digest', type = 'source')
trying URL 'https://cran.revolutionanalytics.com/src/contrib/digest_0.6.25.tar.gz'
Content type 'application/octet-stream' length 145642 bytes (142 KB)
==================================================
downloaded 142 KB

* installing *source* package ‘digest’ ...
** package ‘digest’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
g++ -std=gnu++11 -I"/home/shilde/R-3.6.2/include" -DNDEBUG   -I/usr/local/include  -fpic  -g -O2  -c SpookyV2.cpp -o SpookyV2.o
In file included from SpookyV2.cpp:14:0:
/usr/local/include/memory.h:104:8: error: ‘_Bool’ does not name a type
 extern _Bool reclaim_space();
        ^
SpookyV2.cpp: In static member function ‘static void SpookyHash::Short(const void*, size_t, uint64*, uint64*)’:
SpookyV2.cpp:42:36: error: ‘memcpy’ was not declared in this scope
         memcpy(buf, message, length);
                                    ^
SpookyV2.cpp: In member function ‘void SpookyHash::Update(const void*, size_t)’:
SpookyV2.cpp:160:64: error: ‘memcpy’ was not declared in this scope
         memcpy(&((uint8 *)m_data)[m_remainder], message, length);
                                                                ^
SpookyV2.cpp:194:66: error: ‘memcpy’ was not declared in this scope
         memcpy(&(((uint8 *)m_data)[m_remainder]), message, prefix);
                                                                  ^
SpookyV2.cpp:221:46: error: ‘memcpy’ was not declared in this scope
             memcpy(m_data, u.p8, sc_blockSize);
                                              ^
SpookyV2.cpp:229:34: error: ‘memcpy’ was not declared in this scope
     memcpy(m_data, end, remainder);
                                  ^
SpookyV2.cpp: In member function ‘void SpookyHash::Final(uint64*, uint64*)’:
SpookyV2.cpp:284:68: error: ‘memset’ was not declared in this scope
     memset(&((uint8 *)data)[remainder], 0, (sc_blockSize-remainder));
                                                                    ^
make: *** [SpookyV2.o] Error 1
ERROR: compilation failed for package ‘digest’
* removing ‘/home/shilde/R-3.6.2/library/digest’
* restoring previous ‘/home/shilde/R-3.6.2/library/digest’

The downloaded source packages are in
        ‘/tmp/Rtmph0lZXj/downloaded_packages’
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
Warning message:
In install.packages("digest", type = "source") :
  installation of package ‘digest’ had non-zero exit status

> sessionInfo()
R version 3.6.2 (2019-12-12)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS:   /home/shilde/R-3.6.2/lib/libRblas.so
LAPACK: /home/shilde/R-3.6.2/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] Rcpp_1.0.4.6

loaded via a namespace (and not attached):
[1] compiler_3.6.2 tools_3.6.2

Is there something obvious that I am missing?

Thank you.

**Comment by eddelbuettel** [comment]
What does `g++ --version` say?

**Comment by hildebs42** [comment]
[shilde@pegasus ~]$ g++ --version
g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by eddelbuettel** [comment]
I don't think that counts as 'too old'.  The [results page at CRAN](https://cloud.r-project.org/web/checks/check_results_digest.html) shows it builds fine everywhere---though that tends to skew towards _newer_ rather than older compilers.

You could try one of the older versions from the archive section:  https://cran.r-project.org/src/contrib/Archive/digest/  The SpookyHash addition is "reasonably" new but has not thrown up problems as far as I know.

**Comment by hildebs42** [comment]
I ran into the same issue with another package. I think it is my gcc version. I will try and install on another machine.

Thanks for your time.

**Comment by eddelbuettel** [comment]
I agree -- I launched a build at RHub to try on an older CentOS. That appears to have worked so I think the ball is in your court and it looks like a local setup issue.  

With that, I'll close this.  If there is a digest issue under it, feel free to reopen.
