### ISSUE TITLE
digest of a function depends on the closure environment

### ISSUE THREAD

**Issue by randy3k** [eddelbuettel/digest#158]
``` r
f <- function(x) x
e <- new.env()
environment(f) <- e

digest::digest(f)
#> [1] "2ab6e8c0579f5d58bf2db7712ebe91b7"
e$x <- 1
digest::digest(f)
#> [1] "73c391c97f33f2c6d5609a4aae598826"
e$x <- 2
digest::digest(f)
#> [1] "aff1f5083252f492a650bd8af666c0c2"
```

<sup>Created on 2020-06-13 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

I reckon it is because `digest` depends on `serialize`. And the closure environment (`e`) was also serialized when `f` was serialized.

**Comment by eddelbuettel** [comment]
Sure. The important part is that 

```r
R> f <- function(x) x
R> e <- new.env()
R> environment(f) <- e
R> 
R> d1 <- digest::digest(f)
R> d2 <- digest::digest(f)
R> identical(d1,d2)
[1] TRUE
R> 
```

The key here is that as long as the environment and function do not change, neither does their digest hash.  So it seems everything is working as planned --- a function simply can have an associated environment.

Or am I missing something else you would like to suggest here?

**Comment by eddelbuettel** [comment]
Closing for lack of follow-up. If there is something to add, please feel free to reopen.

**Comment by randy3k** [comment]
Sorry for the late reply.
It is not a bug report per see. I reported this because I was beaten by this a bit earlier.

Users may not notice that the digest of a function also depends on the closure environment. I guess it worths putting down some documentation about the limitations or behavior of the serialization.

It is particularly confusing as the global environment is not serialized.
``` r
f <- function(x) x

digest::digest(f)
#> [1] "2fb645236cec0d43293c00909bbbf82f"
x <- 1
digest::digest(f)
#> [1] "2fb645236cec0d43293c00909bbbf82f"


e <- new.env()
g <- function(x) x
environment(g) <- e

digest::digest(g)
#> [1] "80051e9779c62ebdc0134f2329b50c4a"
e$x <- 1
digest::digest(g)
#> [1] "9e82eac66a89f2b8c049ad40ad20f3c2"
e$x <- 2
digest::digest(g)
#> [1] "92c30ec2352d6bb6d7f29b07d0a5be3a"
```

<sup>Created on 2020-07-17 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by eddelbuettel** [comment]
>  not a bug report per see

Yep, that what it seems like.

> it [is] worth[~s~] putting down some documentation

Yes. How about if I draft a paragraph under Notes for the main manual page?
