### ISSUE TITLE
Long vector support relied on, but not available

### ISSUE THREAD

**Issue by drknexus** [eddelbuettel/digest#16]
Processing a large R object (that otherwise behaves well with most manipulations in R) results in an error with `digest`.  Specifically:
```
Error in digest(user_action, algo = "md5") : 
  long vectors not supported yet: memory.c:3361
```
Nearly identical errors (just the call is different) occur for other algorithms.  Using debug I can see that the error is triggered at `val <- .Call(digest_impl, object, as.integer(algoint), as.integer(length), as.integer(skip), as.integer(raw), as.integer(seed))`; which I believe either places the error in `.Call` or in `digest`.  Memory.c appears to be outside of the scope of `digest` but belongs to R instead.  Nevertheless, because I'm able to work with and manipulate this object in every other context it makes me think that some step along the way in `digest` is the root of the problem.

Example data:
```
eg <- data.frame(V1=rep("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",100000000),V2=runif(100000000),V3=rep("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",100000000),V4=rep("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",100000000),V5=rep("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",100000000))
digest(eg)
```

Session Info:
```
R version 3.2.2 (2015-08-14)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 14.04.3 LTS

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8       
 [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] digest_0.6.8

loaded via a namespace (and not attached):
[1] tools_3.2.2
```

Perhaps something else could be done in the digest internals to make it not rely on memory.c or an overly large object could be detected, truncated, and a hash returned with a warning?

**Comment by eddelbuettel** [comment]
There are two things here:
- yes, we should support long vectors and the `as.integer()` etc obviously currently limits it
- the error comes from `src/main/memory.c` which at the end has

```c
#ifdef LONG_VECTOR_SUPPORT
R_len_t NORET R_BadLongVector(SEXP x, const char *file, int line)
{
    error(_("long vectors not supported yet: %s:%d"), file, line);
}
#endif
```

which itself gets called from two macros in `Rinternals.h`:

```c
# define XLENGTH(x) (IS_LONG_VEC(x) ? LONG_VEC_LENGTH(x) : SHORT_VEC_LENGTH(x))
# define XTRUELENGTH(x) (IS_LONG_VEC(x) ? LONG_VEC_TRUELENGTH(x) : SHORT_VEC_TRUELENGTH(x))
# define LENGTH(x) (IS_LONG_VEC(x) ? R_BadLongVector(x, __FILE__, __LINE__) : SHORT_VEC_LENGTH(x))
# define TRUELENGTH(x) (IS_LONG_VEC(x) ? R_BadLongVector(x, __FILE__, __LINE__) : SHORT_VEC_TRUELENGTH(x))
```

It may just be a matter of replacing use `LENGTH` with `XLENGTH` etc pp.  I'll consult with @thirdwing  who pretty much single-handedly updated Rcpp for this issue.   That may also (finally) get us from using .C to using .Call :)

**Comment by thirdwing** [comment]
I will look into this. Please wait for a moment.

**Comment by eddelbuettel** [comment]
That was quick :)   But no hurry--we can tackle this next week when I am back from Japan.  Or maybe I look on the plane ....  

`digest()` is so tiny, and the underlying algos all work on C-level vectors, that we should be able to lift this indeed as suggested in this ticket.
