### ISSUE TITLE
hash value of on.exit statements

### ISSUE THREAD

**Issue by knthls** [eddelbuettel/digest#160]
I found an interesting phenomenon, while debugging an application that uses the [memoise](https://github.com/r-lib/memoise) package. Memoise creates hashes of `body(some_function)` for cache invalidation. Now if there is an on.exit statement involved, the hash value changes:

```
fun <- function() {
  on.exit({
    print("foo")
  })
  "bar"
}

print(digest(body(fun)))
fun()
print(digest(body(fun)))
```
creates a different hash, after fun is evaluated for the first time. I wonder if this is expected behavior, and if there is a solution other than re-writing the on.exit statement (which is probably the easiest workaround). However it took me forever to find out why memoise needs two evaluations to actually cache my results and I don't quite see why the hashes are different.

**Comment by eddelbuettel** [comment]
:man_shrugging: 

We `digest()` what `serialize()` gives us.  So I would suspect calling `fun()` with an `on.exit()` changes _something_ in the enclosing environment.

**Comment by knthls** [comment]
Ok, thanks for the quick reply. I see how this is not an Issue with `digest`. I think I'll try to factor out the `on.exit` statements.
