### ISSUE TITLE
Possible performance improvements

### ISSUE THREAD

**Issue by wch** [eddelbuettel/digest#163]
I'm doing some work on the memoise package, and have found that the performance of `digest()` could be improved with some simple changes.

If the input to `digest()` is large, then the bottleneck is the hashing algorithm (which is something I don't want to mess with). However, when the input is small, then the bottleneck is miscellaneous in the R code, some of which can be easily improved.

When a user calls a memoized function with small inputs, the overhead from this R code can be significant. I've put a profile of a run here:
https://rpubs.com/wch/671614

To reproduce a similar profile, you need to be running R 3.6 (there's a bug in the profiler in R 4.0 that makes it not record the top of the call stack, rendering it almost useless).

```R
# Install digest with source refs
install.packages("digest", INSTALL_opts = "--with-keep.source", type = "source", 
                 repos = "https://cloud.r-project.org/")

library(digest)
profvis::profvis({
  for (i in 1:20000) {
    digest(123)
  }
})
```

The total time is 590ms. Of that:

* 180ms is spent in `match.arg()`
* 80ms is spent in `::` (for `base::serialize`)

So 44% of the time spent in that code, and those can easily be optimized. I'm happy to provide a PR if that would help.

**Comment by eddelbuettel** [comment]
Howdy, and thanks for reaching out.  You are in very good company -- `digest` is so old (first commit 17 years this month and I was so rookie in R then) that John Chambers himself roasts me and the package in the 2008 SoDA book  :man_facepalming: 

Kidding aside, I like the premise. I mostly don't want to rock the boat w.r.t. to actual hashing as the package is pretty widely used.  But careful rejigging is definitely possibly, just how we added vectorised ops last year around this time.

**Comment by eddelbuettel** [comment]
And maybe before you go off and too deep into it, can you sketch what you'd change?

**Comment by wch** [comment]
The changes are simple:

* For `::`, simply get rid of it and call `serialize()`; and in NAMESPACE, add `importFrom(base,serialize)`
* For `match.arg()`, provide `choices` explicitly, instead of having it infer the possible choices automatically. I think the possible choice inference is the main bottleneck. I haven't tested, but on top of that, it may be noticeably faster to replace `match.arg()` with another function that does just what is needed here.

**Comment by eddelbuettel** [comment]
I think the `base::serialize()` was a belatedly addition to be on the safe side if not even a bug fix -- I would need to check.  Now, given the age of the package, that may well have been before `NAMESPACE`s came into play but how else do we guarantee we get the `serialize()` we want?  AFAICR there is no `importFrom()` for `base`.

I don't really want to play Code Golf just for playing's sake. I as maintainer owe my users some stability.  That may have a higher weight than shaving an msec here or there.  So you would have to convince of valuable yet simple enough changes -- I buy the 'running `algo %in% ...` once and not twice quite

**Comment by wch** [comment]
I get the concerns about stability -- I've been there myself. But I think the proposed changes are solid and will provide a noticeable performance benefit.

I don't think there's a need to worry about `serialize` referring to the wrong object. That may have been true in the days before R had namespaces, but not anymore. The parent environment of the namespace is the package's imports environment; in turn, its parent is a copy of the base environment, and its parent is the global environment. (From there, if you follow the parents, you'll get to the "regular" base environment.)

So if `digest()` calls `serialize()` instead of `base::serialize()`, the only way for another object named `serialize` to interfere is if it's in the digest namespace, or in the imports.

<details>
<summary>Example showing environment structure</summary>

```R
ns <- getNamespace("digest")
ns
#> <environment: namespace:digest>

imports <- parent.env(ns)
imports
#> <environment: 0x7fd711e45a90>
#> attr(,"name")
#> [1] "imports:digest"
ls(imports)
#> [1] "packageVersion"

base_ns <- parent.env(imports)
base_ns
#> <environment: namespace:base>
exists("serialize", base_ns)
#> [1] TRUE


global <- parent.env(base_ns)
global
#> <environment: R_GlobalEnv>

pryr::parenvs(global, all = TRUE)
#> Registered S3 method overwritten by 'pryr':
#>   method      from
#>   print.bytes Rcpp
#>    label                            name               
#> 1  <environment: R_GlobalEnv>       ""                 
#> 2  <environment: package:stats>     "package:stats"    
#> 3  <environment: package:graphics>  "package:graphics" 
#> 4  <environment: package:grDevices> "package:grDevices"
#> 5  <environment: package:utils>     "package:utils"    
#> 6  <environment: package:datasets>  "package:datasets" 
#> 7  <environment: package:methods>   "package:methods"  
#> 8  <environment: 0x7fd73106a400>    "Autoloads"        
#> 9  <environment: 0x7fd72151de00>    "tools:callr"      
#> 10 <environment: base>              ""                 
#> 11 <environment: R_EmptyEnv>        ""
```

</details>


As for the `match.arg()` part, the simplest change, providing `choices` directly, is extremely low-risk and will provide a significant speed-up. In this simple test, it speeds up the `match.arg()` call by about 65%.

```R
f <- function(a=c("a", "b", "c")) {
  match.arg(a)
}

g <- function(a=c("a", "b", "c")) {
  match.arg(a, choices = c("a", "b", "c"))
}

microbenchmark::microbenchmark(
  f(),
  g()
)
#> Unit: microseconds
#>  expr   min    lq      mean median     uq       max neval
#>   f() 5.310 5.452 153.35730 5.5410 5.6845 14743.854   100
#>   g() 1.647 1.753  17.60016 1.8925 1.9605  1560.267   100
```

**Comment by eddelbuettel** [comment]
Colour me convinced and thanks for walking me through the (sealed) namespace aspect.   So I'd say fire the PR over.  We're on the same page in aiming for net improvements at lowest risk of collateral damage.
