### ISSUE TITLE
digests of identical functions are not identical, but sha1 are

### ISSUE THREAD

**Issue by renozao** [eddelbuettel/digest#166]
I understand that the digest of a function takes into account its environment, and the values of the variables in that environment affects the hash.

For the purpose of a caching mechanism that relies on `digest::digest` I would like to ensure that a function defined within some local environment gets the same hash.
I thought that forcing the function's environment to `baseenv()` would do, but here is what I get:

* results from `digest()` are different:
```
> digest::digest(({a <- 1; f <- function(x) x; environment(f) <- baseenv(); f}))
[1] "e9f25660feb5446274486b756d87c7b3"
> digest::digest(({a <- 2; f <- function(x) x; environment(f) <- baseenv(); f}))
[1] "fe191fdb05a01323dd594e085ca9ebdd"
```

* results from `sha1()` are the same:
```
> digest::sha1(({a <- 1; f <- function(x) x; environment(f) <- baseenv(); f}))
[1] "8e09df86c25e070f2e5716da32d951aefe31a8b5"
> digest::sha1(({a <- 2; f <- function(x) x; environment(f) <- baseenv(); f}))
[1] "8e09df86c25e070f2e5716da32d951aefe31a8b5"
```  

I must be missing something.
I am running version 0.6.26.

**Comment by eddelbuettel** [comment]
Hm, can you try to 'trace' the calls and see where they may differ?  Ultimately "all" we do here is call `serialize()` on an object and then invoke a hashing function on the raw vector result.  So without checking my guess is that that `sha1` code path drop the environment along the way before calling `serialize()`.

**Comment by renozao** [comment]
`sha1()` has an argument `environment` that is a flag to control keeping or not the function's environment.
The hash is different if dropping the environment, but it is consistent across the calls:

```
> digest::sha1(({a <- 1; f <- function(x) x; environment(f) <- baseenv(); f}), environment = TRUE)
[1] "8e09df86c25e070f2e5716da32d951aefe31a8b5"
> digest::sha1(({a <- 2; f <- function(x) x; environment(f) <- baseenv(); f}), environment = TRUE)
[1] "8e09df86c25e070f2e5716da32d951aefe31a8b5"
> digest::sha1(({a <- 1; f <- function(x) x; environment(f) <- baseenv(); f}), environment = FALSE)
[1] "f3bd5f325d4352dfea021f76514cd16d22006ea4"
> digest::sha1(({a <- 2; f <- function(x) x; environment(f) <- baseenv(); f}), environment = FALSE)
[1] "f3bd5f325d4352dfea021f76514cd16d22006ea4"
```
How can I trace the call stack all the way down to `serialize`?

**Comment by eddelbuettel** [comment]
I put 'trace' in quotes because I would just look at the source...

**Comment by renozao** [comment]
So `sha1.function()` eventually calls `digest()` on a list object that it includes or exclude the environment hash depending on argument `environment`.

From what I saw in the source of `digest()`, the serialization step would amount to:

```
f1 <- local({a <- 1; f <- function(x) x; environment(f) <- baseenv(); f})
f2 <- local({a <- 2; f <- function(x) x; environment(f) <- baseenv(); f})
s1 <- serialize(f1, connection = NULL, ascii = FALSE, version = 2)
s2 <- serialize(f2, connection = NULL, ascii = FALSE, version = 2)
all.equal(s1, s2)
```
and this gives the very similar yet different outputs:

```
[1] "2 element mismatches"
```

**Comment by eddelbuettel** [comment]
I think you just want to copy what the `sha1` code does an digest a function _sans_ environment:

```r
R> stripenv <- function(x) list(formals=formals(x), body=as.character(body(x)))
R> 
R> digest(local({x <- 1; function(x) x+x}))              # with local env, two different hash sums
[1] "10637b174858ed391d75ce425cddc975"
R> digest(local({x <- 2; function(x) x+x}))
[1] "e633a8bc656faa093fb3dd676ef46075"
R> 
R> digest(stripenv( local({x <- 1; function(x) x+x})) )  # with local env 'stripped away' two identical hashes
[1] "a829f453e8e60bcd62088c4859df0446"
R> digest(stripenv( local({x <- 2; function(x) x+x})) )
[1] "a829f453e8e60bcd62088c4859df0446"
R> 
```

**Comment by renozao** [comment]
The problem is that I am not controlling the call to `digest()`, which is done on the function object itself.
Plus the caching mechanism should in fact reflect the environment in general, but in some cases I want to force disregarding the environment.
I checked that setting the function's environment to `baseenv()` does not change the base env and it doesn't (at least the hash is the same). A bit puzzling.
Thanks for the help.

**Comment by eddelbuettel** [comment]
I am not really sure how to help you here.  Maybe you can modify `digest` locally and do the `stripenv()` equivalent.  If that helps then we could discuss if there is a need or use for a new argument to digest, or maybe a global `option()`, or ...

**Comment by renozao** [comment]
There is nothing to modify in `digest`. The caching mechanism needs to do a plain `digest()` and take into account the environment.
It is the desired behaviour and the reason why I expected identical hash with identical environments.
In fact we get:
```
> identical(f1, f2)
TRUE
```
I find it strange that `serialize()` returns 2 different values on 2 objects that `identical()` cannot distinguish, but there must be a reason behind it.
Will have to send this out to the dev mailing list.

**Comment by eddelbuettel** [comment]
I am going to close this here as I do not think we established an error in `digest` here.  Please feel free to reopen if you think there is an issue with `digest`.
