### ISSUE TITLE
Two kind of zeros that produce different digests?

### ISSUE THREAD

**Issue by Gillis** [eddelbuettel/digest#169]
I run automated regression tests on results from my R code by rounding  the resulting matrix to six decimals + hashing. After years of running smoothly, a certain code producing a large xts failed, without me being able to see any difference in the result using R. This was not caused by any attributes of the data structure, as I strip that out before regression testing.

I actually tracked down the difference to one particular cell, containing something that R tells me contains the number zero. I saved it in this RDS https://drive.google.com/file/d/1-F3g5r5DjEkE1esn-3ycUIxxojMZqnT1/view?usp=sharing .

As you can see.

```r
> reproduce <- loadRDS("reproduce.RDS")
>
> lapply(reproduce,str)
 num 0
 num 0
> identical(reproduce$foo,reproduce$bar)
[1] TRUE
> reproduce$foo == reproduce$bar
[1] TRUE
> reproduce$foo == 0
[1] TRUE
> reproduce$bar == 0
[1] TRUE
> digest(reproduce$foo)
[1] "b01ec9609569aecde321d7dd2674f6e1"
> digest(reproduce$bar)
[1] "908d1fd10b357ed0ceaaec823abf81bc"
> digest(0)
[1] "908d1fd10b357ed0ceaaec823abf81bc"
```

So clearly foo is the fake zero. I notice, there is one difference in the binary serialization of the object

```r
> serialize(reproduce$foo,NULL)
 [1] 58 0a 00 00 00 03 00 04 00 03 00 03 05 00 00 00 00 06 43 50 31 32 35 32 00 00 00 0e 00 00 00 01 **80** 00 00 00 00 00 00 00
> serialize(reproduce$bar,NULL)
 [1] 58 0a 00 00 00 03 00 04 00 03 00 03 05 00 00 00 00 06 43 50 31 32 35 32 00 00 00 0e 00 00 00 01 00 00 00 00 00 00 00 00
```

It even appears to survive rounding

```r
> serialize(round(reproduce$foo),NULL)
 [1] 58 0a 00 00 00 03 00 04 00 03 00 03 05 00 00 00 00 06 43 50 31 32 35 32 00 00 00 0e 00 00 00 01 **80** 00 00 00 00 00 00 00
```

How is this possible? R has two distinct representation for the number zero?

**Comment by eddelbuettel** [comment]
One thing I only recently learned is that _numeric_ zero can apparently be positive _and_ negative.

```r
> digest(reproduce$bar)
[1] "908d1fd10b357ed0ceaaec823abf81bc"
> digest(-reproduce$foo)
[1] "908d1fd10b357ed0ceaaec823abf81bc"
> 
```

So taking 'negative `foo`' produces the same as `bar` as does taking absolute values or integers:

```r
> identical(digest(abs(reproduce$foo)), digest(abs(reproduce$bar)))
[1] TRUE
> identical(digest(as.integer(reproduce$foo)), digest(as.integer(reproduce$bar)))
[1] TRUE
> 
```

So with that I'd say the ball is back in your court as the _sign difference_ on zero is a type of rounding error.  There _is_ a different payload here so we should get different hashes.  Now the _meaning_ of the nunbers is the same, but we know about computers and "do as I say" versus "do as I mean".  I think you need an extra processing step at your end.

**Comment by Gillis** [comment]
Oh damn. You are fully correct in that Dirk. Should have thought about that! Thank you.

I guess this is mostly an annoyance in the UI of R, that negative zeros are not represented -0 as they are in other numeric computation environments (e.g. Matlab, Mathematica at least).
