### ISSUE TITLE
[feature] Add crc32c algorithm

### ISSUE THREAD

**Issue by DyfanJones** [eddelbuettel/digest#183]
Hi all,

I am currently the maintainer of the package paws (R sdk into AWS). AWS has recently released some extra check sum algorithms when working with AWS S3 (https://aws.amazon.com/blogs/aws/new-additional-checksum-algorithms-for-amazon-s3/).

- sha1
- sha256
- crc32
- crc32c

The only algorithm I am missing is **crc32c**. Is it possible for the **crc32c** algorithm to be implemented in `digest`? 

Many thanks in advance

**Comment by eddelbuettel** [comment]
Hi there -- that's probably something we can do.  Do you have a proper source for crc32c -- ideally one that is portable?  I know the AWS SDK for C++ has this in https://github.com/awslabs/aws-checksums but a nice and simple (if slower) standalone would be good.

**Comment by DyfanJones** [comment]
From the looks of it Botocore uses https://github.com/awslabs/aws-crt-python that ultimately uses the repo you have found.

I believe Google has an implementation https://github.com/google/crc32c. As my C and C++ is super limited I am not sure how portable it is or how it compares to AWS implementation.

**Comment by eddelbuettel** [comment]
Yes I found the Google but note that [contains dozens of specialised implmentations](https://github.com/google/crc32c/tree/main/src).  I'd rather not do that.  I'll poke some more.

**Comment by eddelbuettel** [comment]
I was able to quickly create a branch and hook the crc32c routine up.  But the bad news is that I am not matching validation output as seen [here](https://stackoverflow.com/questions/20963944/test-vectors-for-crc32c) and [here](https://www.rfc-editor.org/rfc/rfc3720#appendix-B.4) so I have to put this on pause.  Sorry.

**Comment by DyfanJones** [comment]
Ah not good, I will look at implementing the other checksum algorithms and loop back around to crc32c in a later release. So there isn't any rush to implement crc32c as of yet. Thanks for having a look at this for me.

**Comment by eddelbuettel** [comment]
I am a bit stunned that the validation results did not square -- the mechanics of wiring this up are just as with the other digesting algos.  I also checked quickly with the Python package Ubuntu has for this.  Very confusing.  But probably not a good idea upload this with non-validated output.  So if you can work around it, great.

**Comment by DyfanJones** [comment]
You probably already tempted this but in the Google repo it has a "portable" crc32c implementation.
https://github.com/google/crc32c/blob/main/src/crc32c_portable.cc
https://github.com/google/crc32c/blob/main/src/crc32c_internal.h

Does this mean this implementation is actually portable?

Apologies if you have already gone through these scripts, it is my lack of C/C++ knowledge coming through :)

**Comment by eddelbuettel** [comment]
Yes my first commit (so far still 'here', haven't pushed) used something just like.  My message, for bookkeeping, was

> Adding crc32c.{c,h}
> 
> Source is https://searchfox.org/mozilla-central/source/xpcom/io/

**Comment by eddelbuettel** [comment]
I think we're in business:

```r
> library(digest)
> digest("The quick brown fox jumps over the lazy dog", algo="crc32c", serialize=FALSE)
[1] "22620404"
> digest("123456789", algo="crc32c", serialize=FALSE)
[1] "e3069283"
> 
```

That seems to match two values from here:  https://stackoverflow.com/questions/20963944/test-vectors-for-crc32c

I am going to push the new branch for this in a second, maybe you will get a chance to test it on your workflow.

**Comment by DyfanJones** [comment]
@eddelbuettel this is amazing news!!!!! :) I can do some tests around python implementation :D

**Comment by eddelbuettel** [comment]
This is the branch:   https://github.com/eddelbuettel/digest/tree/feature/crc32c

**Comment by DyfanJones** [comment]
Initial testing against python `awscrt` package.

``` r
library(digest)
  crc32c_base64enc <- function(string) {
    digest(string, algo="crc32c", serialize=FALSE) |>
      substring(c(1,3,5,7), c(2,4,6,8)) |> strtoi(16) |>
      base64enc::base64encode()
  }
  
  crc32c_base64enc("The quick brown fox jumps over the lazy dog")
#> [1] "ImIEBA=="
  crc32c_base64enc("123456789")
#> [1] "4waSgw=="
  crc32c_base64enc("hello-world")
#> [1] "9Fch2w=="
  crc32c_base64enc("this is amazing")
#> [1] "cRVfIg=="
```

<sup>Created on 2023-04-30 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

```python
from awscrt import checksums as crt_checksums
import base64

def crc32c_base64enc(string):
    new_checksum = crt_checksums.crc32c(string, 0)
    int_crc32 = new_checksum & 0xFFFFFFFF
    bs = int_crc32.to_bytes(4, byteorder="big")
    return base64.b64encode(bs).decode("ascii")

crc32c_base64enc("The quick brown fox jumps over the lazy dog")
'ImIEBA=='
crc32c_base64enc("123456789")
'4waSgw=='
crc32c_base64enc("hello-world")
'9Fch2w=='
crc32c_base64enc("this is amazing")
'cRVfIg=='
```

It looks like you have cracked it 😄

**Comment by eddelbuettel** [comment]
Can you pipe both of them into `sprintf("%08x", val)` --- I think Python might use `hex()`.  It is a bit more common to print those results as hex.

But yeppers, I like the look of the comparison to Python.

**Comment by DyfanJones** [comment]
Sure thing:

``` r
library(digest)
digest("The quick brown fox jumps over the lazy dog", algo="crc32c", serialize=FALSE)
#> [1] "22620404"
digest("123456789", algo="crc32c", serialize=FALSE)
#> [1] "e3069283"
digest("hello-world", algo="crc32c", serialize=FALSE)
#> [1] "f45721db"
digest("this is amazing", algo="crc32c", serialize=FALSE)
#> [1] "71155f22"
digest("some extra stuff", algo="crc32c", serialize=FALSE)
#> [1] "f831b4a7"
```

<sup>Created on 2023-04-30 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>


```python
from awscrt import checksums as crt_checksums

def crc32c(string):
    checksum = crt_checksums.crc32c(string)
    return '{:#08x}'.format(checksum)

crc32c("The quick brown fox jumps over the lazy dog")
'0x22620404'
crc32c("123456789")
'0xe3069283'
crc32c("hello-world")
'0xf45721db'
crc32c("this is amazing")
'0x71155f22'
crc32c("some extra stuff")
'0xf831b4a7'
```

**Comment by DyfanJones** [comment]
R side won't pipe into sprintf("%08x", val) as it returns the error:
```
Error in sprintf("%08x", val) : 
  invalid format '%08x'; use format %s for character objects
```

**Comment by eddelbuettel** [comment]
Sorry, think of my part -- what I ship from `digest` already _is_ a 'hex-formatted value' coming in as string.  On pure numerics it works

```r
> val <- 255
> sprintf("%x", val)
[1] "ff"
> val <- 255L
> sprintf("%x", val)
[1] "ff"
> 
```

**Comment by eddelbuettel** [comment]
I may have something better for you --- I was interested in working out the mechanics and I now have

- a new package `crc32c` that provides the algorithm with hardware acceleration when SSE2 or arm64 are present
- a modified `digest` package that uses this package _optionally_ if it is available (I don't want to add a new dependency)
- this is then picked up automagically, else we do what we currently do with is the software-based fallback

The main thing is that it requires you to compile locally to get it.  Worth it?

**Comment by DyfanJones** [comment]
Sounds interesting 😄 plus it keeps digest as light weight as possible 😄 

I'm interested to see what it would look like in practise. 😄

**Comment by DyfanJones** [comment]
That is amazing you have released crc32c so quickly to the cran. I won't be able to test out the branch until I am back from my holiday. I am back on Friday and more than happy to do any testing that is required 😄

**Comment by eddelbuettel** [comment]
No rush.  This offerd a rather nice exercise -- how to take advantage of `cmake`, and how to re-use a (small) static library -- that I was motivated to construct the small example.   We'll get to proper use from `digest` when you're back.
