### ISSUE TITLE
Make endianness for crc32c non constant?

### ISSUE THREAD

**Issue by eddelbuettel** [eddelbuettel/digest#190]
We currently have a constant:

https://github.com/eddelbuettel/digest/blob/3cc41ecf734ca0afa1af9f0563f71c601dca1ec4/src/crc32c/crc32c_config.h#L8-L9

This could be generalized to a one-time configure check and simple `sed` call to create, say, `crc32c_config.h` from a ``crc32c_config.h.in`.   Maybe @barracuda156 wants to lead that change?

**Comment by barracuda156** [comment]
Thank you.

We can perhaps make it without configure, if that is preferable, but just via adding a macro.

Something like:
```
#if defined(__BIG_ENDIAN__) || (defined(__BYTE_ORDER__) && defined(__ORDER_BIG_ENDIAN__))
#define BYTE_ORDER_BIG_ENDIAN 1
#else
#define BYTE_ORDER_BIG_ENDIAN 0
#endif
```
What do you think?

I will check for correct macros now.

**Comment by eddelbuettel** [comment]
Yes, in principle in favor of macros, but also unsure if they are (or are not) standardized.  As we do live in a little-endian world I would like prefer a default of 0 and _if_ one more known macros are defined, a switch to one.  

I am sure I had to deal with this before, probably even in this repo.  But I do not recall right what the canonical solution was :-/

**Comment by barracuda156** [comment]
Here is what Boost uses: https://www.boost.org/doc/libs/1_81_0/boost/endian/detail/order.hpp

> As we do live in a little-endian world I would like prefer a default of 0 and if one more known macros are defined, a switch to one.

This makes perfect sense.

**Comment by eddelbuettel** [comment]
I think I had been here before:  https://sourceforge.net/p/predef/wiki/Endianness/

**Comment by barracuda156** [comment]
As long as we ensure that Big-endian is set to 1 only when specific macro(s) evaluate to 1, and otherwise default is 0, that should be good, IMO.

**Comment by barracuda156** [comment]
So yeah, continuing here. The macros used appear to be consistent. I have tested for Big-endian, it works, at least with GCC, but Clang is said to support those as well.

This is from `abseil` code:
```
  341 // Checks the endianness of the platform.
  342 //
  343 // Notes: uses the built in endian macros provided by GCC (since 4.6) and
  344 // Clang (since 3.2); see
  345 // https://gcc.gnu.org/onlinedocs/cpp/Common-Predefined-Macros.html.
  346 // Otherwise, if _WIN32, assume little endian. Otherwise, bail with an error.
  347 #if defined(ABSL_IS_BIG_ENDIAN)
  348 #error "ABSL_IS_BIG_ENDIAN cannot be directly set."
  349 #endif
  350 #if defined(ABSL_IS_LITTLE_ENDIAN)
  351 #error "ABSL_IS_LITTLE_ENDIAN cannot be directly set."
  352 #endif
  353 
  354 #if (defined(__BYTE_ORDER__) && defined(__ORDER_LITTLE_ENDIAN__) && \
  355      __BYTE_ORDER__ == __ORDER_LITTLE_ENDIAN__)
  356 #define ABSL_IS_LITTLE_ENDIAN 1
  357 #elif defined(__BYTE_ORDER__) && defined(__ORDER_BIG_ENDIAN__) && \
  358     __BYTE_ORDER__ == __ORDER_BIG_ENDIAN__
  359 #define ABSL_IS_BIG_ENDIAN 1
  360 #elif defined(_WIN32)
  361 #define ABSL_IS_LITTLE_ENDIAN 1
  362 #else
  363 #error "absl endian detection needs to be set up for your compiler"
  364 #endif
```
http://docs.ros.org/en/lunar/api/abseil_cpp/html/base_2config_8h_source.html
