### ISSUE TITLE
digest::digest() bakes some internal memory-management flags into the hash

### ISSUE THREAD

**Issue by dvg-p4** [eddelbuettel/digest#197]
As in https://stackoverflow.com/questions/75413666/hash-identical-r-dataframes-different-hashes-not-an-attribute-problem

This can also be seen by comparing the `digest::digest()` of vectors in a large data.frame read in by `data.table::fread()` with data.table version 1.14.0 vs 1.14.8 (the latter will have that `GROWABLE_MASK` bit set).

Unfortunately, I'm not sure if it'd be possible to fix this in a backwards-compatible way.

**Comment by eddelbuettel** [comment]
Your problem is with `serialize()` , the base R function that turns _any_ R object into a raw string vector.  `digest()` then merely applies a hashing function of your choosing over the string.

It is a little bit like this:

```r
> foo <- 3.14
> bar <- foo
> attr(bar, "bling") <- "glam"  # could be any attribute, any value
> all.equal(foo, bar)
[1] "Attributes: < target is NULL, current is list >"
> all.equal(foo, bar, check.attributes=FALSE)
[1] TRUE
> 
```

Which is why for example the popular unit test packages have both `test_equal()` and `test_equivalent()` where the latter skips attributes.

So I think you should address this at your end, if you can, which 'sanitizing' function that runs over objects before you pass them to `digest`.  It could for example drop the `GROWABLE_MASK` bit.  (I happen to flip between CRAN's `data.table` 1.4.8 and the long-running-not-released-yet 1.4.9.)

**Comment by dvg-p4** [comment]
Yeah, I noticed that you seem to strip out the R-version magic numbers from the serialization, wondered if it would be possible to strip these out; but these do seem significantly more baked-in. Any suggestions what do use for a sanitizing function, since the internal gp bits aren't really meant to be user-accessible? `data.table::copy()` seems to clear them, but I'm a bit worried about whether that will continue to work across future versions (since it's again, internal non-guaranteed behavior).

**Comment by eddelbuettel** [comment]
I am not doing anything, I just call `serialize()`.  It has options.

The problem seem to be entirely in your corner.  If you have an issue with `data.table` you need cleanse the object it creates.

**Comment by dvg-p4** [comment]
Yeah I understand, the core problem here is that R is baking in its internal memory management flags into its serialization format. So I'd be happy to try to solve the problem on my end, but I'm kind of at a loss as to how to do so, since AFAICT there are no user-friendly ways to set or unset these bits (in fact I get the strong impression they're intentionally supposed to be inaccessible for memory-integrity reasons).

So, any advice for "cleansing" objects pre-hashing? Like, is there a function I can call that will generally scrub this kind of metadata from an R object? `data.table::copy()` seems to work for now, as mentioned above, but it would be nice if there were an option that didn't, well, have to make a giant copy. Or that explicitly specified clearing these bits as documented behavior.

**Comment by eddelbuettel** [comment]
I would think  you need a C(++) level function to clear or remove a bit in the SEXP data structure.

**Comment by dvg-p4** [comment]
Ah well. Perhaps the core issue here is, well, trying to hash an entire multi-megabyte dataframe I'm reading in from a text file, with unrounded floating point values, with all the various bits and bobs still attached, and attempting use it as a unique identifier across multiple years of package updates.

Regardless, thanks for the pointers!

**Comment by eddelbuettel** [comment]
Now we're talking.  You could just copy the data into a new / clean / fresh object and hash that.  But I think we established that the 'change arrow' seems to point your way rather that to the `digest` repo so I will allow myself to close this.

Should you find any actual shortcomings in `digest` please do not hesitate to either reopen this, or create a new issue.
