### ISSUE TITLE
vector to digest function

### ISSUE THREAD

**Issue by jangorecki** [eddelbuettel/digest#2]
Is there any more efficient way to turn vector of characters into vector of its hashes then presented below?

``` r
col <- c("asd1","asd2","asd3","asd2","asd1")
masking <- function(col) vapply(col, function(object) digest(object, algo="md5"), FUN.VALUE = "", USE.NAMES = FALSE)
masking(col)
col
```

and not only for `md5`

**Comment by eddelbuettel** [comment]
Release 0.6.21, which should hit CRAN today, has a fully vectorized version. Speed gains are demonstrated by a new little demo vectorised.R.
