### ISSUE TITLE
sha1() versus digest()

### ISSUE THREAD

**Issue by StEvUgnIn** [eddelbuettel/digest#202]
Please consider adding this answer to the article and citing the site and the author from the link below:
https://stackoverflow.com/questions/77281804/r-why-digestalgo-sha1-produces-different-answer-to-sha1

**Comment by eddelbuettel** [comment]
I do not contribute any more to StackOverflow. If you want to write there, feel free to. I see no issue at the `digest` repo so closing this as non-issue.

**Comment by eddelbuettel** [comment]
Your post is also a little hard to grok for me. You talk about adding something (call it 'A') to something else (call it 'B') and then provide one link.  Is that A or B?  Where is the other?  What do you want added?  Why?  Anyway, I am sure you take care of it...

**Comment by eddelbuettel** [comment]
The need for `skip=...` is pretty well documented in the 20-year history of `digest`.  The package _primarily_ digests R objects and works on the output of `serialize()` so it is not primarily a hash function for given strings.  But, as documented, one can use that too and all the tests of particular algos do.
