### ISSUE TITLE
digest fails to build with recent r-devel builds

### ISSUE THREAD

**Issue by kevinushey** [eddelbuettel/digest#208]
The most recent r-devel builds now set `STRICT_R_HEADERS` on by default, which implies that these APIs are no longer available:

https://github.com/wch/r-source/blob/af085e9ea6c901381101afa8e3a8275a2ecdf95d/src/include/R_ext/RS.h#L52-L59

These are currently reported on CRAN under the "Strict" checks, as per https://www.stats.ox.ac.uk/pub/bdr/Strict/digest.out, but recent NEWS entries suggest this will likely be the default in the next release.

Fortunately, the fixes should be straightforward, and I can prepare a PR.

**Comment by eddelbuettel** [comment]
Nice. How did you catch it, ie what `digest` builds do you follow?  I am on slightly reduced attention-span this week as I am on vacation in :canada: ?

(As it happens, I had actually tooted on mastodon about this very change and trumpeted our horn as `Rcpp` had defaulted to this for years now ... but `digest` is of course not a client of `Rcpp` as it predates it ...)

**Comment by kevinushey** [comment]
In my case, I just spotted it because I was testing out a recent version of R-devel on macOS, and bumped into this while reinstalling a variety of packages.

Enjoy the vacation in Canada, I hear it's a beautiful place ;-)

**Comment by eddelbuettel** [comment]
Hah!  I would undoubtedly have heard from CRAN in due course, maybe I can exempt that with an upload once they open again.
