### ISSUE TITLE
Cannot install latest version

### ISSUE THREAD

**Issue by kirillseva** [eddelbuettel/digest#21]
Looks like my R is unable to parse the description file.
```r
R version 3.1.2 (2014-10-31) -- "Pumpkin Helmet"

> install_github('eddelbuettel/digest')
Using github PAT from envvar GITHUB_PAT
Downloading github repo eddelbuettel/digest@master
Error: Found continuation line starting ' The md5 algorithm b ...' at begin of record.
> Sys.info()
                                                                                           sysname
                                                                                          "Darwin"
                                                                                           release
                                                                                          "14.3.0"
                                                                                           version
"Darwin Kernel Version 14.3.0: Mon Mar 23 11:59:05 PDT 2015; root:xnu-2782.20.48~5/RELEASE_X86_64"
                                                                                           machine
                                                                                          "x86_64"
```

**Comment by kirillseva** [comment]
I see, it's same thing as https://github.com/eddelbuettel/drat/issues/1

**Comment by kirillseva** [comment]
And looks like it's solved here: https://github.com/hadley/devtools/commit/ed3475f117b768cd5f14b8fca1b72cdc0717a32f

Well, at least future generations would know that updating devtools solves this particular type of error! :)

**Comment by eddelbuettel** [comment]
I don't really care. I don't develop for, or use,  `devtools::install_github`.  If you think you need to live of the development source the _fork or clone the darn repo_.

**Comment by eddelbuettel** [comment]
Actually, would you care to try the brand-new riff by @gaborscardi on this?   A new package [install](https://github.com/MangoTheCat/install) without any extra depends, possibly going to be the refactored installer @hadley mentioned once or twice?

[ That said, I remain on record as stating that installing of randomly user-chosen snapshot from third-party repositories is fundamentally _broken_.  The R Community has an established release protocol for a good reason, and it friggin' _works_.  Depart from it at your peril. ]

**Comment by gaborcsardi** [comment]
Wait guys, that package is not ready..... Sorry.

It should have a large 

# Unfinished

header or something.

**Comment by eddelbuettel** [comment]
My bad.  Let me grab my time machine and revert the recommendation.  It just shows you just how much karma you have around here :)

**Comment by eddelbuettel** [comment]
Next up: A pull request to [mason](https://github.com/metacran/mason) to default to a big fat UNFINISHED...

**Comment by gaborcsardi** [comment]
Yeah, indeed.
