### ISSUE TITLE
Add some examples on writing sha1() method for classes not handled by digest

### ISSUE THREAD

**Issue by ThierryO** [eddelbuettel/digest#22]
I would suggest to add this as a vignette. I'm willing to write it.

- Do you prefer Sweave/LaTeX/pdf or knitr/markdown/HTML? 
- I have some fancy examples for `lme4` and `INLA`. I could work something out for mainstream models like `lm` or `glm`.

**Comment by eddelbuettel** [comment]
In favour.  I tend(ed) to favour real Rnw/tex for things where I eventually hoped to publish it (and I have a mixed track record following through; some are out; some have been pending for a while).  I have started to add some vignettes from .Rmd.  

It depends on the scope.  For a quick vignette on just this feature Rmd is fine.  Do we enough drive to get this further?  I would be in favour of an R Journal piece too -- in fairness to other digest contributors that probably would need to cover more.  

Both are not exclusionary.  What are your thoughts?

**Comment by ThierryO** [comment]
The [`rticles` package](https://github.com/rstudio/rticles) has a Rmd templates for the R Journal and the Journal of Statistical Software. Hence I suggest to start with a quick vignette on `sha1()` in Rmd. Maybe some vignette(s) on other parts of `digest`.  If we write the vignette(s) Rmd with the journals in mind, it should be easy to combine them into an article written in Rmd.

**Comment by eddelbuettel** [comment]
Yes, I tend to have that (unfinished) package installed as well.  Might as well start there.   Let's just aim for something simple(r) [ie R Journal] with the recent additions in mind and go from there?

**Comment by ThierryO** [comment]
That's fine. I'll brew something on `sha1()`.

1. The difference between `sha1()` and `digest()`
1. When to use `sha1()` and when `digest()`
1. Some examples and guidelines on writing new methods for `sha1()`

**Comment by eddelbuettel** [comment]
:+1:

**Comment by ThierryO** [comment]
I've added a first crude draft to the [vignette](https://github.com/ThierryO/digest/blob/vignette/vignettes/sha1.Rmd) branch of my fork.

What is the easiest way for you to comment on it? As a pull request on you repo or as comments on my fork?

**Comment by eddelbuettel** [comment]
I'd say just forge ahead and PR it.  We can iterate then.

**Comment by eddelbuettel** [comment]
With digest 0.6.9 on CRAN, I'll close this.
