### ISSUE TITLE
sha1() fails if x contains an empty list

### ISSUE THREAD

**Issue by mllg** [eddelbuettel/digest#27]
Small example:
```r
sha1(list())
sha1(list(a = 1, b = list()))
```

**Comment by eddelbuettel** [comment]
Ooops.  Has an element of pilot error but maybe we should test more.

@ThierryO do you want to take a stab at this?

**Comment by ThierryO** [comment]
I'll have a look at it

**Comment by ThierryO** [comment]
PR #28 should solve the problem.

**Comment by eddelbuettel** [comment]
Closing as #28 has been merged.

**Comment by ThierryO** [comment]
This issue is still open ;-)

**Comment by eddelbuettel** [comment]
PRs welcome.

**Comment by vsimko** [comment]
```r
sha1(list())
sha1(list(a = 1, b = list()))
```
... both do work, should this issue be close already ?

**Comment by eddelbuettel** [comment]
Maybe. Any consensus view?  Any view by @mllg?

**Comment by ThierryO** [comment]
IMHO this is resolved. You can close the issue.

**Comment by eddelbuettel** [comment]
Will do.
