### ISSUE TITLE
Install failure on R < 3.0.0

### ISSUE THREAD

**Issue by mvkorpel** [eddelbuettel/digest#29]
My attempt to install "digest" on R 2.15.3 failed with the following error message:

```
** testing if installed package can be loaded
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '<FOO>/lib/R/library/digest/libs/digest.so':
  <FOO>/lib/R/library/digest/libs/digest.so: undefined symbol: XLENGTH
Error: loading failed
Execution halted
ERROR: loading failed
```

where `<FOO>` denotes the `--prefix` path where R was installed.

Installation succeeds on R 3.0.0. I suspect that the `Depends` field in `DESCRIPTION` is outdated.

**Comment by eddelbuettel** [comment]
We could probably make use of that conditional on R being > 3.0.0 and fall back to LENGTH otherwise.

But honestly: why are you using R 2.15.3?   And if you need it and think you need to insist on it, why not limit yourself to equally outdated packages?  ;-)

**Comment by eddelbuettel** [comment]
Can you try the two-liner I just committed in https://github.com/eddelbuettel/digest/commit/24e214fe3eb7609128d80ed8082c826accbba288 ?

**Comment by mvkorpel** [comment]
Thanks, it works now. As to your earlier question, I only use the old R for testing.

**Comment by eddelbuettel** [comment]
Thanks for the confirmation.
