### ISSUE TITLE
Project website points to R-Forge

### ISSUE THREAD

**Issue by nuest** [eddelbuettel/digest#31]
Not sure this is the right place to report, but sending an Email seems weird!

Anyway, the project web page http://dirk.eddelbuettel.com/code/digest.html points to the no longer used R-Forge project... "at the R-Forge host."

The [project overview page](http://dirk.eddelbuettel.com/code/) correctly points to GitHub.

**Comment by eddelbuettel** [comment]
If it is my personal site, email is perfectly fine.  

This one was weird. The source page had this removed, but the generated html page did not. I corrected that.

Thanks for the heads-up.
