### ISSUE TITLE
sha1.list() should allow vectors for the digits and zapsmall arguments

### ISSUE THREAD

**Issue by ThierryO** [eddelbuettel/digest#32]
In case a list() we could allow digits and zapsmall to be either a single number or a vector with the same length as the list. The vector allows the user the specify a different value for digits and zapsmall for each element of the list. The current default remain.

Use case: a list with e.g. a data element and a model. For the data we can use a high value for digits (e.g. 14). For the model we will need a smaller value for digits (e.g. 7).

**Comment by eddelbuettel** [comment]
You could also pre-process your data with a local function.

I don't really see this as being a key feature for littler.   Call it 'wontfix'.
