### ISSUE TITLE
WISH: Streamed/incremental digestion?

### ISSUE THREAD

**Issue by HenrikBengtsson** [eddelbuettel/digest#33]
Would it be possible to make a version of `digest()` to incrementally calculate the checksum.  Conceptually something like:

``` r
x <- 1:10
digester <- new_digest(algo="md5")
digester <- add_to_digest(digester, object=x[1:5])
digester <- add_to_digest(digester, object=x[6:10])
checksum <- close_digest(digester)
stopifnot(identical(checksum, digest(x, algo="md5"))
```
# Background

I've got large (~5 GiB) data files that contains ~20-100 genomic sequences.   My goal is to generate a checksum for each individual sequence - so not the whole file.  I know the start and stop file positions of each sequence so I can read them in individually using a file connection (via random access).  What complicates my genomic files is that it contains auxiliary newlines (CR, LF, or CRLF) that are (i) OS dependent and (ii) that may occur at say every 50:th or 80:th character ("different line wrap widths depending on source).  I want my checksum to ignore these newlines.

Yes, I could open a connection, skip to the start of the sequence of interest, read all of the sequence into memory, drop all newlines, and call `digest(clean_seq)`.  However, ideally I'd like to be able to do this with constant-memory constraints.  Hence my wish.

**Comment by eddelbuettel** [comment]
Well, ex ante a lot of things are possible.

Contributors such as yourself have pushed digest beyond what it was originally designed to do. We could keep expanding with clean PRs that do not impact existing interfaces.   

From what you describe, I'd think (very naively) that maybe one needs an intermediating layer watching the stream and 'end of segment' markers before submitting the now-determined segment.  But there may be better ways...

**Comment by vsimko** [comment]
Hi there, the following code covers your requirement of constant memory usage.
Moreover, it also runs parsing the 5GB file and computing the digest in parallel.
Hopefully it helps, although there is certainly space for improvements. (e.g. I'm not sure if this works on Windows)

```r
library(parallel)
library(digest)

x <- as.character(1:10) # input from your example

fname <- "mystream.fifo" # choose name for your named pipe
close(fifo(fname, "w")) # creates your pipe if does not exists

producer <- mcparallel({
    mystream <- file(fname, "w")
    writeLines(x[1:5], mystream)
    writeLines(x[6:10], mystream)
    close(mystream) # sends signal to the consumer (digester)
})

digester <- mcparallel({
    digest(fname, file = TRUE, algo = "md5") # just reads the stream till signalled
})

# runs both processes in parallel
mccollect(list(producer, digester))

unlink(fname) # named pipe removed
```

**Comment by HenrikBengtsson** [comment]
Thanks @vsimko for this.

A few minor comments:
* `writeLines(x, sep="\n")` has the annoying habit to translate the LF to CRLF on Windows.  Because of this you wouldn't get the same result on different platforms.  Using `writeLines(x, sep="")` solved this.

* `writeBin(x, endian="little", con=con)` should work with any data type, e.g.
```r
library("parallel")
library("digest")

x <- as.character(1:10) # input from your example

fname <- "mystream.fifo" # choose name for your named pipe
close(fifo(fname, open="wb")) # creates your pipe if does not exist

producer <- mcparallel({
    mystream <- file(fname, open="wb")
    writeBin(x[1:5], endian="little", con=mystream)
    writeBin(x[6:10], endian="little", con=mystream)
    close(mystream) # sends signal to the consumer (digester)
})

digester <- mcparallel({
    digest(fname, file = TRUE, algo = "md5") # just reads the stream till signalled
})

# runs both processes in parallel
md5 <- mccollect(list(producer, digester))[[2]]
print(md5)
## [1] "25867862802a623c16928216e2501a39"
```

* Unfortunately, which is what I'd really like to achieve, writing/serializing an R object and passing the serialized version to `digest()` does not give the same result as calling it directly on the R object itself, e.g.
```r
digest::digest(x, algo = "md5")
## [1] "f9c1814034ec2dd6f08647c3bef181c8"
```


Yes, it's correct that `mcparallel()` is not available on Windows, but (allowing for some self promotion) with the [future](https://cran.r-project.org/package=future) package one can with some minor tweaks rewrite your examples as:
```
library("future")
## Use multicore/process forking;
## iff not supported fall back to multiple R background sessions (e.g. Windows)
plan(multiprocess)

x <- as.character(1:10) # input from your example

fname <- "mystream.fifo" # choose name for your named pipe
close(fifo(fname, open="wb")) # creates your pipe if does not exists

producer <- future({
    mystream <- file(fname, open="wb")
    writeBin(x[1:5], endian="little", con=mystream)
    writeBin(x[6:10], endian="little", con=mystream)
    close(mystream) # sends signal to the consumer (digester)
})

digester <- future({
    digest::digest(fname, file = TRUE, algo = "md5") # just reads the stream till signalled
})

md5 <- value(digester)
print(md5)
## [1] "25867862802a623c16928216e2501a39"
```
You should get the same result on any platform.

Using implicit futures, one can clean this up further:
```r
library("future")
plan(multiprocess)

x <- as.character(1:10) # input from your example

fname <- "mystream.fifo" # choose name for your named pipe
close(fifo(fname, open="wb")) # creates your pipe if does not exists

producer %<-% {
    mystream <- file(fname, open="wb")
    writeBin(x[1:5], endian="little", con=mystream)
    writeBin(x[6:10], endian="little", con=mystream)
    close(mystream) # sends signal to the consumer (digester)
}

# just reads the stream till signalled
md5 %<-% digest::digest(fname, file = TRUE, algo = "md5")
print(md5)
## [1] "25867862802a623c16928216e2501a39"
```

**Comment by HenrikBengtsson** [comment]
@vsimko, I forgot to write that, I do _indeed_ think that what you're suggest could work for my problem where I'm interested in calculating MD5 checksums for parts of the 5 GiB file.  I do need to read in the DNA sequence strings and drop newlines (LF, CRLF, CR, ...) in order to get consistent results regardless of line endings.  But with your approach of having one process producing input to a FIFO file that `digest()` digests it should be possible to do this in small chunks.  So, yes, it's certainly an interesting workaround you've proposed for my problem (and even better that it also work on Windows which I do need to support as well)  I'll report back when I get a chance to implement this - which might take a few weeks (before I get back to that project).

**Comment by vsimko** [comment]
Thanks for the example with futures!

**Comment by eddelbuettel** [comment]
We have this now with version 0.6.19 and spookyhash.
