### ISSUE TITLE
What about roxygen-generated documentation?

### ISSUE THREAD

**Issue by vsimko** [eddelbuettel/digest#35]
Currently, the content of `man/*.Rd` files is created manually.

Many packages, such as `dplyr` use `roxygen` to generate the man pages from doc-comments.
- It also allows to separate examples into `R` files instead of writing them directly to `Rd` files (`@example` tag).
- `NAMESPACE` file can be generated this way from `@exports` and `@useDynLib` tags.

Would something like this be desired in `digest` package?

**Comment by eddelbuettel** [comment]
`digest` is a little special as it is a) small, b) self-contained, c) is fairly widely used and d) has a stable API.

As such I have *very* little desire to make wholesale change, or even small changes that just amount to [bike shedding](https://en.wikipedia.org/wiki/Law_of_triviality).  So no, _converting_ existing Rd files is of no interest.

Don't get me wrong. I like and use `roxygen2` for other projects, and new documentation. [ But I do not let it touch `DESCRIPTION` or `NAMESPACE`. ]  So in short 'thanks for the interest but no thanks'.  We do have some open issue tickets for things we consider missing; I do not feel that this needs to be added.

**Comment by vsimko** [comment]
Makes sense.
I'm closing this issue then.
