### ISSUE TITLE
Possible relicensing of digest from GPL-2 to GPL (>= 2) 

### ISSUE THREAD

**Issue by eddelbuettel** [eddelbuettel/digest#36]
digest was started 13 years ago in 2003. At the time GPL-2 was the only game in town; the GPL-3 did AFAIK not arrive until 2007.   

It has been pointed out to me that in order to use digest along with software licensed _only_ under the GPL-3, it would be preferable to use either "GPL (>= 2)" or "GPL-2 | GPL-3" (which is what CRAN currently expands the former to).

I am ok with the idea of relicensing from "GPL-2" to "GPL (>= 2)" [1] but I am under the understanding that _every_ copyright holder needs to agree.  So based on the DESCRIPTION file, this means we need to hear from everybody below (in chronological order of contributions to digest): 

- [x] Dirk Eddelbuettel @eddelbuettel 
- [x] Antoine Lucas (no known GitHub handle)
- [x] Jarek Tuszynski (no known GitHub handle, old work email that was said to bounce)
- [x] Henrik Bengtsson @HenrikBengtsson
- [x] Simon Urbanek @s-u
- [x] Mario Frasca @mfrasca
- [x] Bryan Lewis @bwlewis
- [x] Murray Stokely @murraystokely
- [x] Hannes Muehleisen @hannesmuehleisen 
- [x] Duncan Murdoch @dmurdoch 
- [x] Qiang Kou @thirdwing 
- [x] Jim Hester @jimhester 
- [x] Wush Wu @wush978 
- [x] Thierry Onkelinx @ThierryO 
- [x] Michel Lang @mllg
- [x] Viliam Simko @vsimko 

I marked myself as being fine with the proposed change, and I plan to accordingly mark everybody who reports back (preferably below with a simple _"I am ok with the license change to GPL (>=2)"_. 

But it is my understanding that we need _everybody_ to report back in order to be operational.  So thanks in advance for giving this some thought, and following-up below.
Thanks to everybody for all the support over these thirteen years -- with all your help digest went _much_ further than I ever imagined.   Let's see if we can pull this one off too, so help in locating everybody listed above (and of course anybody I may have forgotten) is welcome!

[1] Also please forgive me for very plainly stating that I have **zero** interest in a license comparison discussion. The digest package has always been under copyleft licensing, and will remain copyleft. This is not the place or time to discuss MIT vs Apache vs BSD vs ...

**Comment by HenrikBengtsson** [comment]
I am ok with the license change to GPL (>=2) /Henrik

**Comment by s-u** [comment]
I am ok with the license change to GPL (>=2) /Simon

**Comment by thirdwing** [comment]
I am ok with the license change to GPL (>=2) /Qiang Kou

**Comment by murraystokely** [comment]
I am ok with the license change to gpl (>=2)

Murray

**Comment by hannesmuehleisen** [comment]
I am ok with the license change to gpl (>=2)

Hannes

**Comment by bwlewis** [comment]
I am ok with the license change to gpl (>=2)

Best,

Bryan

**Comment by mllg** [comment]
I am ok with the license change to GPL (>=2).

Michel

**Comment by ThierryO** [comment]
I am ok with the license change to GPL (>=2) 

Thierry

**Comment by jimhester** [comment]
I am ok with the license change to GPL (>=2)

Jim

**Comment by wush978** [comment]
I am ok with the license change to GPL (>=2) 

Wush

**Comment by eddelbuettel** [comment]
I heard from Antoine Lucas he said in private mail:

```
Date: Fri, 29 Apr 2016 15:58:24 +0200                                                                                                                                                                               
From: Antoine Lucas <....>                                                                                                                                                                        
To: Dirk Eddelbuettel <edd@debian.org>                                                                                                                                                                              
Subject: Re: Proposed license change of digest from 'GPL-2' to 'GPL (>= 2)'                                                                                                                                         

Hello.

I am on holiday. I have no objection to a change on GPL version.

Do as you prefer.

Bests

Antoine Lucas
```

**Comment by vsimko** [comment]
I am ok with the license change to GPL (>=2) /Viliam

**Comment by mfrasca** [comment]
I am ok with the license change to GPL (>=2) :smile:

**Comment by dmurdoch** [comment]
I'm also okay with it.

**Comment by eddelbuettel** [comment]
The entity making the request for the relicensing found a workaround, so this is now less urgent.

I will leave it open; if someone ever finds Jarek Tuszynski on-line or in real-life please direct him here.  It would be nice to bring it to closure, whether it is somewhat urgent (as it once was) or not (now).

**Comment by JarektCommons** [comment]
I am also find with the relicense

**Comment by eddelbuettel** [comment]
Hey -- so good to hear from you!   We are now (tada) in _complete_ agreement so the next upload will be GPL (>= 2).  It just so happens ... that I made one to CRAN today which just arrived as 0.6.10.  But there is no (longer any) hurry.
