### ISSUE TITLE
BUG: digest(..., file=TRUE, skip=n) for n > 0 fails

### ISSUE THREAD

**Issue by HenrikBengtsson** [eddelbuettel/digest#39]
The `skip` parameter with `file=TRUE` is handled just as when `file=FALSE` resulting in the following bug:
```r
> digest::digest("DESCRIPTION", file=TRUE)
[1] "1c282839cdd654d02ecda6ecbab30cbe"

> digest::digest("DESCRIPTION", file=TRUE, skip=1L)
Error in digest::digest("DESCRIPTION", file = TRUE, skip = 1L) :
  Cannot open input file: ESCRIPTION
```

# Troubleshooting
I spotted this bug by visual inspection of the code.  It's because of the following in [src/digest.c](https://github.com/eddelbuettel/digest/blob/master/src/digest.c#L71-L78), which is called unconditionally on `file`:
```c
    if (skip>0) {
        if (skip>=nChar) {
            nChar=0;
        } else {
            nChar -= skip;
            txt += skip;
        }
    }
```

I'll try to find time to fix this, but I'll add this issue here so it won't be forgotten.

**Comment by eddelbuettel** [comment]
Very nice work.  Thanks for taking the time to tackle this.
