### ISSUE TITLE
URL in DESCRIPTION should point to github ?

### ISSUE THREAD

**Issue by vsimko** [eddelbuettel/digest#40]
The URL field in DESCRIPTION file currently points to http://dirk.eddelbuettel.com/code/digest.html
I think it should point to https://github.com/eddelbuettel/digest because then it would be easier for services such as http://depsy.org/package/r/digest to properly compute "research software impact" for all contributors.

**Comment by vsimko** [comment]
I also created a relatd issue in the `Impactstory/depsy` repository https://github.com/Impactstory/depsy/issues/62

**Comment by eddelbuettel** [comment]
Maybe. Maybe not. I am maintainer, and [dirk.eddelbuettel.com/code] is my top-level URL for projects.

If depsy cannot crawl, isn't that a problem with depsy.

I suggest to close this.
