### ISSUE TITLE
R CMD check on Travis = WARNING

### ISSUE THREAD

**Issue by vsimko** [eddelbuettel/digest#46]
```
* checking package vignettes in ‘inst/doc’ ... WARNING
Package vignette without corresponding PDF/HTML:
   ‘sha1.Rmd’
* checking running R code from vignettes ...
   ‘sha1.Rmd’ using ‘UTF-8’ ... OK
 NONE
* checking re-building of vignette outputs ... SKIPPED
* DONE
Status: 1 WARNING
```
**Note:** This link might help: https://www.r-bloggers.com/continuous-integration-for-r-packages/

**Comment by eddelbuettel** [comment]
I am lost here --  what is the point you are trying to make?

Ie what is the issue you are trying ro raise here?  That vignettes are not being built in _my_ package's Travis setup?   That is generally _on purpose_ as I do not install a full texlive environment.

**Comment by eddelbuettel** [comment]
For what it is worth, I am one of the co-authors of the (older, first-generation) Travis setup for R, and the maintainer of the 'fork' continuing its approach --- so I do the things I do largely on purpose.  I see no shortcoming but maybe you can explain to me what bugs you here?

**Comment by vsimko** [comment]
When I tried to build my fork of `digest` on Travis, I saw the WARNING message.
Then, I realized that the warning is also visible in upstream https://travis-ci.org/eddelbuettel/digest
I know that the vignettes are not built on purpose, but I couldn't find a workaround for this warning.

**Comment by eddelbuettel** [comment]
You mean the `sha1.Rmd` above?  I don't generally consider Travis runs to be the "final word". That happens here where I have R-devel available etc pp.    And/or use extra tools, under which everything is perfectly clean.  This uses `rcc.r`, a little helper from the littler package using something by Gabor which aggregates/pretty-prints/uses color (lost in copying here):

```bash
edd@max:~/git/digest(master)$ rcc.r
────────────────────────────────────────────────────────────────────────────────
─  using log directory ‘/tmp/file2702619dad48/digest.Rcheck’
─  using R version 3.3.1 (2016-06-21)
─  using platform: x86_64-pc-linux-gnu (64-bit)
─  using session charset: UTF-8
✔  checking for file ‘digest/DESCRIPTION’
─  this is package ‘digest’ version ‘0.6.10’
✔  checking package namespace information
✔  checking package dependencies
✔  checking if this is a source package
✔  checking if there is a namespace
✔  checking for executable files
✔  checking for hidden files and directories
✔  checking for portable file names
✔  checking for sufficient/correct file permissions
✔  checking whether package ‘digest’ can be installed
✔  checking installed package size
✔  checking package directory
✔  checking ‘build’ directory
✔  checking DESCRIPTION meta-information
✔  checking top-level files
✔  checking for left-over files
✔  checking index information
✔  checking package subdirectories
✔  checking R files for non-ASCII characters
✔  checking R files for syntax errors
✔  checking whether the package can be loaded
✔  checking whether the package can be loaded with stated dependencies
✔  checking whether the package can be unloaded cleanly
✔  checking whether the namespace can be loaded with stated dependencies
✔  checking whether the namespace can be unloaded cleanly
✔  checking loading without being on the library search path
✔  checking dependencies in R code
✔  checking S3 generic/method consistency
✔  checking replacement functions
✔  checking foreign function calls
✔  checking R code for possible problems
✔  checking Rd files
✔  checking Rd metadata
✔  checking Rd cross-references
✔  checking for missing documentation entries
✔  checking for code/documentation mismatches
✔  checking Rd \usage sections
✔  checking Rd contents
✔  checking for unstated dependencies in examples
✔  checking line endings in C/C++/Fortran sources/headers
✔  checking compiled code
✔  checking installed files from ‘inst/doc’
✔  checking files in ‘vignettes’
✔  checking examples
✔  checking for unstated dependencies in ‘tests’
✔  checking tests
✔  checking for unstated dependencies in vignettes
✔  checking package vignettes in ‘inst/doc’
─  checking running R code from vignettes ...
      ‘sha1.Rmd’ using ‘UTF-8’ ... OK
    NONE
✔  checking re-building of vignette outputs
✔  checking PDF version of manual

── 0 errors ✔ | 0 warnings ✔ | 0 notes ✔
edd@max:~/git/digest(master)$ 
```

I also run a R-devel wrapper.  As they are all squeaky-clean, I will close the issue here.

**Comment by eddelbuettel** [comment]
> I know that the vignettes are not built on purpose, but I couldn't find a workaround for this warning.
> (I also tried --no-manual)

I think it is in fact a simple side-effect of suppressing vignettes [as we do here](https://github.com/eddelbuettel/r-travis/blob/master/run.sh#L31).  You would need a different `R CMD check` invocation.
