### ISSUE TITLE
Change default hash function from md5 to xxhash64 for speed & space efficiency

### ISSUE THREAD

**Issue by gwern** [eddelbuettel/digest#48]
The digest package documentation clearly warns that the cryptographic hash functions provided in digest like MD5, SHA-256 or SHA-512, are not intended for security purposes:

> Please note that this package is not meant to be deployed for cryptographic purposes for which more comprehensive (and widely tested) libraries such as 'OpenSSL' should be used.

Presumably they are provided for convenience and compatibility purposes. However, cryptographic hash functions are typically slower than regular hash functions and their hashes are also longer, leading to more CPU & RAM consumption. And as one would expect, some simple microbenchmarking suggests that the slowdown, particularly on large inputs, could be substantial when using SHA or MD5 compared to the fastest lightweight hash, xxhash64 (which I understand is optimized for the now-universal 64-bit platforms R is used on):

    library(digest)
    library(microbenchmark)
    x <- runif(100000)
    microbenchmark(times=1000, unit="us", digest(x, algo="md5"), digest(x, algo="sha1"), digest(x, algo="sha256"), digest(x, algo="sha512"), digest(x, algo="crc32"), digest(x, algo="murmur32"), digest(x, algo="xxhash32"), digest(x, algo="xxhash64"))
    # Unit: microseconds
    #                          expr      min        lq         mean     median         uq        max neval   cld
    #       digest(x, algo = "md5") 2485.131 2786.4570  4295.136380  4764.8345  5072.0785  98563.923  1000   c
    #      digest(x, algo = "sha1") 3567.551 3883.1065  5958.170993  6745.6465  7060.6915  99762.800  1000    d
    #    digest(x, algo = "sha256") 6611.958 7162.4820 10632.041292 12650.1370 12971.2000  79189.573  1000     e
    #    digest(x, algo = "sha512") 3572.797 3930.3560  6271.029691  6775.0555  7085.4540 101179.334  1000    d
    #     digest(x, algo = "crc32") 1446.463 1661.5915  2656.618527  2728.0760  3029.7340  96977.578  1000  b
    #  digest(x, algo = "murmur32") 1068.145 1317.6815  2040.655517  2064.6110  2372.3685  73234.312  1000 a
    #  digest(x, algo = "xxhash32")  909.042 1115.3040  1824.721796  1716.8020  2022.8500  76509.794  1000 a
    #  digest(x, algo = "xxhash64")  830.653 1066.3930  1627.243898  1614.8140  1916.8650   4083.643  1000 a
    x2 <- runif(100)
    microbenchmark(times=1000, unit="us", digest(x2, algo="md5"), digest(x2, algo="sha1"), digest(x2, algo="sha256"), digest(x2, algo="sha512"), digest(x2, algo="crc32"), digest(x2, algo="murmur32"), digest(x2, algo="xxhash32"), digest(x2, algo="xxhash64"))
    # Unit: microseconds
    #                           expr    min      lq      mean  median      uq      max neval cld
    #       digest(x2, algo = "md5") 48.368 50.2300 55.479182 50.9320 51.6655 2322.038  1000  b
    #      digest(x2, algo = "sha1") 51.628 53.4765 56.321293 54.1390 54.8600 1886.369  1000  bc
    #    digest(x2, algo = "sha256") 60.406 62.4860 63.602296 63.1400 63.9570   87.782  1000   c
    #    digest(x2, algo = "sha512") 47.967 49.8710 50.851533 50.5745 51.3650   67.580  1000 ab
    #     digest(x2, algo = "crc32") 43.503 45.7115 50.358762 46.2845 47.0430 1878.604  1000 ab
    #  digest(x2, algo = "murmur32") 41.907 44.3050 47.264461 44.9710 45.8590 1893.419  1000 a
    #  digest(x2, algo = "xxhash32") 41.688 43.9555 47.075301 44.6250 45.3780 1895.936  1000 a
    #  digest(x2, algo = "xxhash64") 41.629 43.8965 44.948122 44.5920 45.3360   62.534  1000 a
    object.size(digest(x, algo="md5")); object.size(digest(x, algo="xxhash64"))
    # 136 bytes
    # 120 bytes

Right now, `digest()` defaults to 'md5'. Any users of digest who want better performance for free must rewrite all calls to change the `algo` parameter, which is not always possible (for example, the `ht` library doesn't let the user change it, and I suspect that is part of why it shows [worse performance and space efficiency compared to environments](https://blog.dominodatalab.com/a-quick-benchmark-of-hashtable-implementations-in-r/) even though it is a trivial wrapper around environments which uses `digest()` to turn arbitrary R objects into keys).

This would require a 2-line change in `digest.r` to change the order of arguments to start with xxhash64:

    digest <- function(object, algo=c("md5", "sha1", "crc32", "sha256", "sha512",
                           "xxhash32", "xxhash64", "murmur32"),   

a change to `README.md` to update the examples' outputs, an update to `digest.Rd` to change the hash algorithm documented as the default and tweak the examples, and I guess similarly in `tests/digestTest.R`/`tests/digestTest.Rout.save` (because they too assume MD5 as the default).

Hopefully, this would result in use of digest just automatically being 5%+ faster for users. A 64-bit hash should avoid any collisions in current users of digest. I'm not sure what implications there might be for people serializing data using digest; are there any use cases where people are using the md5 hashes of objects as permanent identifiers? (Are these hashes even invariant across R versions?) It wouldn't be hard for them to change their digest use to force MD5 use (or maybe just rethink why they want a big slow broken cryptographic hash like MD5 in the first place, which offers neither performance nor security...) So it might require a version bump & warning note.

**Comment by eddelbuettel** [comment]
You have to understand that the R package ecosystem works as well as it does -- and it does work exceptionally well -- it that people are generally careful about making _breaking_ changes to other packages, particularly widely used packages.

And digest is fairly widely used -- I currently count 108 packages. Some of these are themselves widely used (think knitr). It is also 10+ years old.  There may well be systems using digest for signatures of stored objects in databases or other repositories.  There is simply no way we can change the default now.

You can always write yourself a local caller `mydigest(...)` calling digest with the arguments you prefer, and if you do indeed identify packages _calling_ digest with fixed arguments maybe you need to talk to their maintainers to enact change.

As for performance, I am aware of at least one 'faster' replacement candidate which IIRC addresses both vectorization and different hash functions.

**Comment by gwern** [comment]
I wondered a little about the compatibility thing and I looked deeper. The serialization is being done by `base::serialize`, which says about this issue:

     These functions have provided a stable interface since R 2.4.0
     (when the storage of serialized objects was changed from character
     to raw vectors).  However, the serialization format may change in
     future versions of R, so this interface should not be used for
     long-term storage of R objects.

So in other words, any package which would be broken by this change was already broken repeatedly up to 2006, may have been broken since then, and digest or its users are directly violating base's documentation & warning if they are using it for long-term storage. If anyone is going to complain about it, they should be talking to core and getting a promise about the serialization actually being stable...

At the very least, I think the documentation for digest could mention that the other hashes are faster and why they shouldn't be relied on for long-term identification/storage.

> As for performance, I am aware of at least one 'faster' replacement candidate which IIRC addresses both vectorization and different hash functions.

Sounds great. I hope it makes it in soon.

**Comment by eddelbuettel** [comment]
You fail to understand that _serialization_ is not the same the _created a hash from the serialized bit stream_.  Neither one is supposed to change, and digest's default hash won't change just because you happen to think we should.

**Comment by gwern** [comment]
I'm not sure I follow... Serialization certainly can and has changed, I just quoted that right from the docs.

And if base can change the serialization at any time, then the hash computed on the serialized representation of an R object will also change and any old uses of the hash become suspect - a hashtable, for example. One had an ID like 'c(1)', serialized it into `58 0a 00 00 00 02 00 03 03 01 00 02 03 00 00 00 00 0e 00 00 00 01 3f f0 00 00 00 00 00 00`, MD5ed it into a short hash `"6717f2823d3202449301145073ab8719"`, and used that as the key in a hashtable for some data; now base changes the serialization as their documentation explicitly warns they have and may yet do, and now it serializes into something else like `59 ... 01`, MD5 results in a completely different hash, and the lookup in the hashtable fails. What am I missing here? How can changes to the serialization of R objects not affect anything at all while you say changes to the hash function would be disastrous?

**Comment by eddelbuettel** [comment]
I have maintained digest long enough to have a feel, and actual experience, for when it changes.  

And you and I are currently discussing how such changes are not desirable.  Which is why `md5` will remain the default.  Thanks for your understanding, but I will now lock this issue and get back to work.

Your applications are free to select any of the other hashing functions, which is why we offer them.  If you feel like contributing another hashing functions, we do have a history of gladly accepting well-written pull requests (particularly with corresponding documentation and tests).
