### ISSUE TITLE
The argument `raw` of `digest` is ineffective

### ISSUE THREAD

**Issue by wush978** [eddelbuettel/digest#58]
Hi Dirk,

I just occasionally found this: 

```
> (.x <- digest::digest("test", "crc32", FALSE, raw = TRUE))
[1] "d87f7e0c"
> class(.x)
[1] "character"
```

According to the documentation, it should be a raw vector, right?

Best,
Wush

**Comment by eddelbuettel** [comment]
Interesting.  We need to track that down.  "Basic" raw use still works:

```r
R> library(digest)
R> digest("test", raw=TRUE)
 [1] 06 19 5a a3 45 d5 f8 88 9b c7 de 7d fe f9 2e 30
R> class(digest("test", raw=TRUE))
[1] "raw"
R> 
```

It seems to work for everything but 'crc32'.

**Comment by eddelbuettel** [comment]
And it is pretty clear when we compare [the code for crc32](https://github.com/eddelbuettel/digest/blob/master/src/digest.c#L115-L125) with the cases before/after: it simply ignores the raw flag.  Should be easy to fix.

**Comment by eddelbuettel** [comment]
I think it is different.  The c code for crc32 returns an unsigned long.  There simply aren't any raw characters here.  

So I think I should just document that crc32 (and xxhas64 and murmur32) do not offer 'raw' return values.

**Comment by eddelbuettel** [comment]
I can shoehorn something in but for a reason I do not understand the output order is reversed:

```
edd@max:~/git/digest(bugfix/issue58)$ r -ldigest -p -e'digest("test", algo="crc32", raw=FALSE)'
[1] "d5d3197c"
edd@max:~/git/digest(bugfix/issue58)$ r -ldigest -p -e'digest("test", algo="crc32", raw=TRUE)'
[1] 7c 19 d3 d5
edd@max:~/git/digest(bugfix/issue58)$ 
```

That is the same 4 pairs, but reverse.  Not too happy with that so I think I would rather leave as is.

Do you need raw output from crc32?

**Comment by eddelbuettel** [comment]
So I have a branch now, but I don't like what it does.  

For now I will just document this in the manual page.

**Comment by wush978** [comment]
Hi Dirk,

I do not need it now. So document this is OK. 

Thanks,
Wush

**Comment by eddelbuettel** [comment]
Ok -- that went in as acaebd2e3b0fa3cbebe023d199d3b374c1d60e12 so I'll close this now.
