### ISSUE TITLE
Consider BLAKE2 or t1ha

### ISSUE THREAD

**Issue by eddelbuettel** [eddelbuettel/digest#60]
See https://blake2.net/

**Comment by eddelbuettel** [comment]
See https://github.com/rurban/smhasher for comparisons.

**Comment by eddelbuettel** [comment]
And https://github.com/leo-yuriev/t1ha as its fastest hash.

**Comment by eddelbuettel** [comment]
And @dirkschumacher wrapped BLAKE3 https://github.com/dirkschumacher/blake3 (from Rust)

**Comment by dirkschumacher** [comment]
There seems to be a C reference implementation as well. But I haven't looked into it.

**Comment by dirkschumacher** [comment]
Would you be ok with putting the [C implemention](https://github.com/BLAKE3-team/BLAKE3/tree/master/c) of blake3 into the package? It is public domain/apache2, but would require maintenance I suppose. Or maybe there is a different way. I would be happy to write a PR.

**Comment by eddelbuettel** [comment]
Yes!  I would open to anything clean and simple enough to not alter the package.  C is great, maybe even C++ would be fine. 

I have not (really) looked into any of the TODO ones listed here; those for mostly markers for "if I am ever bored with an empty desk and no other programming tasks" style notes.  And we know how that works.

**Comment by eddelbuettel** [comment]
And `blake3` is master so closing this.
