### ISSUE TITLE
Please provide release tags

### ISSUE THREAD

**Issue by epipping** [eddelbuettel/digest#61]
It would be nice if e.g. 9c64bfb1d8df2a92c2d427e8fb6f0c2ef47e02de was tagged as 0.6.12.

**Comment by eddelbuettel** [comment]
Maybe. It's manual work.  The git repo really is to be seen as an internal side effect.

The history of digest is [here on CRAN](https://cloud.r-project.org/src/contrib/Archive/digest/).

**Comment by epipping** [comment]
One of the advantages would be: Having a stable URL through which a 0.6.12 tarball could be obtained. Once the next digest release is out, the CRAN download URL will cease to worked since 0.6.12 will be moved to the archive.

**Comment by eddelbuettel** [comment]
Gosh, no.  Did you click on the first of the two links I provided?  Please do.  

_All_ tarballs going back to 2003 and digest 0.1.0.

**Comment by epipping** [comment]
Yes, I did. I did not say that old tarballs are removed. I'm just saying:

- Today if you want to download the tarball for digest-0.6.12 from CRAN, the URL is https://cloud.r-project.org/src/contrib/digest_0.6.12.tar.gz
- Once the next release comes out, the tarball will be moved; the URL will become https://cloud.r-project.org/src/contrib/Archive/digest/digest_0.6.12.tar.gz

The implication is: The former URL works today but not in the future and the latter will work in the future but doesn't yet today.

**Comment by eddelbuettel** [comment]
It is a perfectly deterministic issue as you know today what today's version is.  For that, top-level.  For all earlier once, archive dir.  For all later ones, time machine.

I *have* built scripts with exactly that logic.  A decade ago.  Nothing changed.

**Comment by eddelbuettel** [comment]
Also. the cran-mirror-on-github has tags:  https://github.com/cran/digest/releases
