### ISSUE TITLE
mumurhash as raw?

### ISSUE THREAD

**Issue by dfalbel** [eddelbuettel/digest#63]
Is it possible to get the results from murmur32 as raw?

I mean, when I run:
```

hash <- digest::digest("foo", "md5", serialize = FALSE, raw = TRUE)
hash
#>  [1] ac bd 18 db 4c c2 f8 5c ed ef 65 4f cc c4 a4 d8
```

This returns a raw vector. But when I change the algorithm to `murmur32`, I get:

```
hash <- digest::digest("foo", "murmur32", serialize = FALSE, raw = TRUE)
class(hash)
#> [1] "character"
```

I don't understand anything about hashes, and maybe this question doesn't make sense.

**Comment by dfalbel** [comment]
For some context, I want to compare murmur32 algorithm with [`mmh3`](https://github.com/hajimes/mmh3) from python.  Should they be equivalent?

**Comment by eddelbuettel** [comment]
That had come up in the very distant past for some other hashes.  From the top of my head there is an option to turn off / suppress the R header and in that case the result should be the same.

Poke in my unit tests as well because I do compare many of the hashes against their known documented and expected output.

**Comment by dfalbel** [comment]
I finally found that 

```
>>> mmh3.hash("foo", 41) + 2**32
3612049630
```
in python is equivalent to:

```
> digest("foo", algo = "murmur32", serialize = FALSE, seed = 41) %>%
     Rmpfr::mpfr(base = 16)
#> 1 'mpfr' number of precision  32   bits 
#> [1] 3612049630
```
 in R.

Thanks!

**Comment by eddelbuettel** [comment]
So the output of 

```r
> library(digest)
> digest("foo", algo = "murmur32", serialize = FALSE, seed = 41)
[1] "d74b80de"
>
```

cannot be created in Python ?

**Comment by dfalbel** [comment]
I couldn't find a way, but I didn't dig too much.. The integer representation was better for me.

**Comment by eddelbuettel** [comment]
Can you explain (very slowly) the underlying trick?  I only ever compared raw vector element.

Are you essentially bitshifting down from 64 bit to 32 and discarding the upper hald?

**Comment by dfalbel** [comment]
I don't really know what I did :P 

First in `python`: `mmh3.hash` returns a 32 bit signed int, so to convert it to an int representation I just added 2^32 by following this: https://stackoverflow.com/a/20768199/3297472

Then in R, I think `digest` with `murmur32` algorithm returns a string representing an integer in base 16. I converted it to the decimal representation using Rmpfr following this answer: https://stackoverflow.com/a/26303434/3297472

**Comment by eddelbuettel** [comment]
I think we can close this.
