### ISSUE TITLE
function object hash changed after running parallel function in Shiny

### ISSUE THREAD

**Issue by dracodoc** [eddelbuettel/digest#65]
@eddelbuettel 
I have some time consuming code using parallel in my Shiny app. I want to memoise it. The code worked in script but failed in Shiny, because my function take a function object, and the hash value of that function object changes after every run of parallel process.

I managed to create a minimal example to show the problem.

```r
# test digest in shiny
library(shiny)
library(digest)
library(memoise)
library(parallel)
# just a random function. byte code compiled system function don't have this problem
test_fun <- function() {
  cat
}
para_test <- function() {
  mclapply(rep(4, 5), mean)
}
para_test_mem <- memoise(para_test)

ui <- fluidPage(actionButton("test", "Test"))
server <- function(input, output){
  observeEvent(input$test, {
    # para_test()
    para_test_mem()
    print(test_fun)
    cat("test_fun digest: ", digest(test_fun), "\n")
  })
}
shinyApp(ui = ui, server = server)
```

- Clicking `test` button of the app will run a memoised parallel function, also print the hash value of `test_fun`. In my app I need to run a function on a list in parallel, so I need a function object as parameter.
- The 1st and 2nd click will have different hash value for `test_fun`. 
  After that the cache worked and no parallel code was executed, `tes_fun` will have consistent hash value.
- If you replace `para_test_mem()` with the original version `para_test`, every click will have consistent hash value.

```r
Listening on http://127.0.0.1:5768
function() {
  cat
}
<environment: 0x129b2b608>
test_fun digest:  7ed2b264b5d080bd0331568ec19dfb4e 
function() {
  cat
}
<environment: 0x129b2b608>
test_fun digest:  3540d38333dbd2181e73294b9f1156ae 
function() {
  cat
}
<environment: 0x129b2b608>
test_fun digest:  3540d38333dbd2181e73294b9f1156ae 
```

The test code above only show problem when the parallel function is memoised. I believe this is because the parallel part is too simple. In my app the parallel part took several seconds, and running the non-memoised parallel function will change hash of another function. If you can find a longer parallel test code, it should have same bug behavior.

- I'm wondering if that is related to the fact that the parallel code created multiple fork then collected result.
- It should not be random seed, right? 
- The environment of `test_fun` is same. And it's defined in the session, should be same in one session.
- R system function is byte code compiled, and they don't have this problem.
- Same code in script instead of Shiny don't have this problem.

**Comment by eddelbuettel** [comment]
Looks to me that it iss your application problem.  You have _different objects_ so you get _different hashes_.

Maybe you want to remove the external pointer, or parent env reference, or whatever comes from _your use of parallel code_.   Flatten that, digest only the value, and they will be the same.   

For that you may have to memoise at the manager level, rather than at the worker.  I have no idea -- but this is not something digest does wrong.

**Comment by dracodoc** [comment]
I'm not suggesting this is a bug of digest. I was wondering if you can have some insight that how this can happen.

- The object should be same. `test_fun` is defined in Shiny session, and should remain same within the session. I printed the function in output, it's same function body in same environment. 
  The code without parallel get same hash on every time, I think this should prove the object is same, and all the changes came from the parallel code.
- In my app memoize is not needed to reproduce the behavior. The test code need memoize because the parallel part is too simple.
- I also don't think the memoize happened on worker. There is no memoized function sent to worker. The function will not run in parallel at all if the parameter meet previous cache.
- There is nothing special in the parallel code. And the most important thing is, the value to be digested have nothing to do with the parallel part in this test code.
- This definitely came from Shiny + parallel, since parallel code in script don't have the problem. Running parallel in Shiny is obvious tricky so I'm not surprised for this behavior, but I was hoping to find out what I can do to avoid it.

Anyway I have realized I can work around this by making a wrapper function and include the function object parameter inside, so the memoize version will not check on function object.

**Comment by eddelbuettel** [comment]
I think it may just be `memoize()` (or whatever it is that triggers it) being "helpful" in adding the outer environment (as you may normally need it) -- but that differs in your use case.  

I did check the arguments to that function and it is one. So maybe overriding helps, maybe stripping down as discussed.   

So to repeat:  I still believe it's your app design.  So no issue for you to file here.  And while I appreciate the enthusiasm you bring, you cannot really expect me to spend my time debugging _your_ app.
