### ISSUE TITLE
Considers sha256() and sha512()

### ISSUE THREAD

**Issue by ThierryO** [eddelbuettel/digest#72]
Those could be equivalent to `sha1()`.

**Comment by eddelbuettel** [comment]
You mean write new wrappers similar to 370+ lines of `R/sha1.R` ?   Sure ...

**Comment by ThierryO** [comment]
I don't need it at the moment. But maybe I will in the future. 

A more elegant solution is probably to give an `algo` argument to `sha1()` which is passed to `digest()`. That would open up the idea behind `sha1()` to all available algorithms.

**Comment by eddelbuettel** [comment]
I like that.  It is sometimes nice to have the additional structure of S4, but I rarely have the energy or appetite to write all the required code.  Now that we have it, it would be nice to reuse it for the "bigger" sha sums.

**Comment by eddelbuettel** [comment]
Thanks for #73 which implements this.
