### ISSUE TITLE
Download failing for El Capitan

### ISSUE THREAD

**Issue by cclatterbuck** [eddelbuettel/digest#76]
Installing digest is not working for RStudio. This prevents knitting R Markdown files. I am on a Mac running El Capitan (v 10.11.6), R version 3.4.3, RStudio 1.1.383. I think this is because CRAN has the El Capitan version digest_0.6.14.tgz whereas the download is looking for digest_0.6.15.tgz. The call & error code is below. 

> install.packages("digest")
Installing package into ‘/Users/biostudent/Library/R/3.4/library’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.4/digest_0.6.15.tgz'
Warning in install.packages :
  cannot open URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.4/digest_0.6.15.tgz': HTTP status was '404 Not Found'
Error in download.file(url, destfile, method, mode = "wb", ...) : 
  cannot open URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.4/digest_0.6.15.tgz'
Warning in install.packages :
  download of package ‘digest’ failed

**Comment by wlandau** [comment]
@cclatterbuck For now, can you `install.packages("digest", type = "source")`? This little delay gets me all the time with [Travis](https://travis-ci.org/) and [AppVeyor](https://www.appveyor.com/). Usually, it just goes away if I wait a little bit. If it persists for more than a day, then maybe something else needs to be done.

**Comment by eddelbuettel** [comment]
Not at a problem _with the package_ which works as expected.

You have a problem with CRAN, but this is not the place to report it.  I have as much control over binary builds at CRAN as you.  Sorry -- but what @wlandau says is the only thing you can do here.

**Comment by cclatterbuck** [comment]
Thanks Will! I'll give that a shot (trying to batch-prep a bunch of laptops
for a class, and they need to be able to knit to HTML).

**Comment by eddelbuettel** [comment]
Looks like something is broken at their (ie CRAN repo) end.  I just got another report (#77) and posted there what I now sent to the r-devel mailing list.

**Comment by eddelbuettel** [comment]
And you can also fetch that digest_0.6.14.tgz "by hand" and just install it locally.  It will give you a fully working version -- the delta to 0.6.15 is truly marginal.
