### ISSUE TITLE
Can't install package

### ISSUE THREAD

**Issue by lrichm** [eddelbuettel/digest#77]
I'm having an issue installing digest in RStudio (version 1.0.153). Here's the error:

> install.packages("digest", dependencies = T)
trying URL 'https://rweb.crmda.ku.edu/cran/bin/macosx/el-capitan/contrib/3.4/digest_0.6.15.tgz'
Warning in install.packages :
  cannot open URL 'https://rweb.crmda.ku.edu/cran/bin/macosx/el-capitan/contrib/3.4/digest_0.6.15.tgz': HTTP status was '404 Not Found'
Error in download.file(url, destfile, method, mode = "wb", ...) : 
  cannot open URL 'https://rweb.crmda.ku.edu/cran/bin/macosx/el-capitan/contrib/3.4/digest_0.6.15.tgz'
Warning in install.packages :
  download of package ‘digest’ failed

I have tried updating my CRAN mirror and have tried restarting my R Studio session, and neither if these solutions worked.  I discovered this error when trying to load lmerTest, as follows:

> library(lmerTest)
Error: package or namespace load failed for ‘lmerTest’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 there is no package called ‘digest’

Any idea why I can't get this package installed?

**Comment by eddelbuettel** [comment]
Please see #76 which I closed an hour ago.

Seriously folks:  Search existing tickets.

**Comment by lrichm** [comment]
My apologies for the oversight.

**Comment by eddelbuettel** [comment]
It's ok--it is a little hard to see.  You are the 3rd person today with that exact same issue, so I just escalated that up to the powers that be.  Looks like the PACKAGES file is off.  

https://stat.ethz.ch/pipermail/r-devel/2018-January/075466.html

**Comment by eddelbuettel** [comment]
And you can also fetch that digest_0.6.14.tgz "by hand" and just install it locally.  It will give you a fully working version -- the delta to 0.6.15 is truly marginal.

**Comment by lrichm** [comment]
That worked perfectly- thank you!
