### ISSUE TITLE
install is failing

### ISSUE THREAD

**Issue by vhertzb** [eddelbuettel/digest#78]
I am trying to install version 0.15 of digest, but it fails. 

1. I tried install.packages from the command line in the RStudio console and it failed:

> install.packages("digest")
trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.4/digest_0.6.15.tgz'
Warning in install.packages :
  cannot open URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.4/digest_0.6.15.tgz': HTTP status was '404 Not Found'
Error in download.file(url, destfile, method, mode = "wb", ...) : 
  cannot open URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.4/digest_0.6.15.tgz'
Warning in install.packages :
  download of package ‘digest’ failed

2. I tried to install it from the unzipped tar.gz that I downloaded and it failed:

> install.packages("~/Users/vicki/Downloads/digest", repos=NULL, type="source", dependencies = c("Depends", "Suggests", "Imports"))
Warning: invalid package ‘/Users/vicki/Users/vicki/Downloads/digest’
Error: ERROR: no packages specified
Warning in install.packages :
  installation of package ‘/Users/vicki/Users/vicki/Downloads/digest’ had non-zero exit status 

I am running R version 3.4.2 within RStudio version 1.1.419.

Thanks in advance for any insight you can offer.

**Comment by eddelbuettel** [comment]
Please see #76 and #77.
