### ISSUE TITLE
digest_0.6.15.tar.gz is advertised in mirrors but isn’t available “Cannot open URL”

### ISSUE THREAD

**Issue by andyanderson** [eddelbuettel/digest#80]
Sorry if this isn’t the right place to report this, not sure where else, but I tried several mirrors, all advertise that digest 0.6.15 for Mac OS X El-Capitan is available but give this error message:

cannot open URL 'https:// . . . /bin/macosx/el-capitancontrib/3.4/digest_0.6.15.tgz'

Changing 15 to 14 lets me download and install it.

Thanks!

**Comment by eddelbuettel** [comment]
Please see tickets #76 to #79.  Good news is that is getting fixed at CRAN.

**Comment by eddelbuettel** [comment]
With respect to #76, #77, #78, #79 and #80 here, this email by Simon indicates that this CRAN-induced error should be fixed "soon": https://stat.ethz.ch/pipermail/r-devel/2018-January/075500.html
