### ISSUE TITLE
All primitive functions have the same digest::sha1() hash

### ISSUE THREAD

**Issue by coolbutuseless** [eddelbuettel/digest#81]
Problem: All primitive functions have the same digest::sha1() hash. 

Expectation: Different primitive functions should have different digest::sha1() hashes.

e.g. 

    > digest::sha1(`+`)
    [1] "098c0ebd5df77c19684f3f8c9aefc3ca810a159b"
    > digest::sha1(`*`)
    [1] "098c0ebd5df77c19684f3f8c9aefc3ca810a159b"

**Comment by eddelbuettel** [comment]
IIRC they dispatch to the same function and then switch on the given operator.  So result is to be expected.

**Comment by eddelbuettel** [comment]
And two _different_ functions gets different hash sums:

```r
R> digest::digest(`+`)
[1] "5aafac832a836d80d76ce6bd33619d83"
R> digest::digest(abs)
[1] "75a5f3bf2bb967f59397c496099365ee"
R> 
```

I suggest we close this.
