### ISSUE TITLE
string -> int hashing

### ISSUE THREAD

**Issue by dselivanov** [eddelbuettel/digest#82]
Hi here. I'm wondering whether it make sense to add simple hash function to hash arbitrary string into 32 bit integer. It seems it is quite common case and everyone reinvents the wheel (I'm opening this issue because I found myself reimplementing this 3rd time for different packages). 

One solution is to use `digest` with `Rmpfr::mpfr`. But it is another pkg and system dependency (`libmpfr`). 

`digest` itself is widely available and would be nice to have simpler built-in solution like [One-at-a-Time](https://en.wikipedia.org/wiki/Jenkins_hash_function#one_at_a_time) or something from this [article](http://eternallyconfuzzled.com/tuts/algorithms/jsw_tut_hashing.aspx). 

I found `One-at-a-Time` works nice - low collision and super fast. I can send PR.

**Comment by eddelbuettel** [comment]
Good idea, and open to it, but I dislike the idea of pulling `mpfr` in for everybody.  We _could_ do it via `Suggests:` and fail gracefully if it is not installed. Better still not to use it. Do I understand you correctly that `One-at-a-Time` works without `mpfr`?

**Comment by dselivanov** [comment]
I think I was not clear. I propose to add one C/C++ function to `digest` which will do string->int hashing.  `Rmpfr`/`mpfr` is not required - thats the main point.

**Comment by dselivanov** [comment]
So should I open PR? What will be suggestion about the name and signature of the function?

**Comment by eddelbuettel** [comment]
Good questions.  I am a little swamped with Rcpp PRs but we can carry this forward.

Maybe `digest2int` or something like this to it clear we are not producing digest strings?
