### ISSUE TITLE
Test currently conditioned on < R-3.5.0 actually depends on detailed R version

### ISSUE THREAD

**Issue by radfordneal** [eddelbuettel/digest#83]
There's a test in sha1Test.R that is currently done only for < R-3.5.0, which checks the following:

        identical(
            sha1(serialize("e13485e1b995f3e36d43674dcbfedea08ce237bc", NULL)),
            "93ab6a61f1a2ad50d4bf58396dc38cd3821b2eaf"
        )

But actually, this test will fail for all but at most one version of R.  This is because "serialize" includes the version of R being run in its output header, so sha1 of that output will be different for every version of R.

**Comment by eddelbuettel** [comment]
Very fair point.  

On the other hand, `digest` is a 15 or more years old package. "They" don't always change the serialization format so this tends to persist for some time. 

Besides not testing this, do you have any clever ideas?  Maybe test the returned value against a version returned by '>=' matched R version?

**Comment by radfordneal** [comment]
It's not that the format has changed (I think there is a new format being introduced, but that's not the issue here).  It's that the format has for many years included the version of R being run as part of the header.  It changes even with updates of the minor number, such as from R-3.4.0 to R-3.4.4.

For instance, here are results with R-3.4.0:

    > serialize("e13485e1b995f3e36d43674dcbfedea08ce237bc", NULL)
     [1] 58 0a 00 00 00 02 00 03 04 00 00 02 03 00 00 00 00 10 00 00 00 01 00 04 00
    [26] 09 00 00 00 28 65 31 33 34 38 35 65 31 62 39 39 35 66 33 65 33 36 64 34 33
    [51] 36 37 34 64 63 62 66 65 64 65 61 30 38 63 65 32 33 37 62 63
    > serialize("e13485e1b995f3e36d43674dcbfedea08ce237bc", NULL) [7:10]
    [1] 00 03 04 00

And here for R-3.4.4:

    > serialize("e13485e1b995f3e36d43674dcbfedea08ce237bc", NULL)          
     [1] 58 0a 00 00 00 02 00 03 04 04 00 02 03 00 00 00 00 10 00 00 00 01 00 04 00
    [26] 09 00 00 00 28 65 31 33 34 38 35 65 31 62 39 39 35 66 33 65 33 36 64 34 33
    [51] 36 37 34 64 63 62 66 65 64 65 61 30 38 63 65 32 33 37 62 63
    > serialize("e13485e1b995f3e36d43674dcbfedea08ce237bc", NULL) [7:10]
    [1] 00 03 04 04

You can see that the version of R being run shows up in bytes 7 to 10.

You could just ignore those bytes, using 

    serialize("e13485e1b995f3e36d43674dcbfedea08ce237bc", NULL) [-(7:10)]

**Comment by eddelbuettel** [comment]
If memory serves, "they" even included an option to skip the version header and just compare the loading. Do options `serialize` and 'skip` not do what we want?

```
> R.version.string
[1] "R version 3.4.4 RC (2018-03-09 r74380)"
> digest("1 2 3 4 5")
[1] "46250feb04b8575bf41b61fa7e4b66c4"
> 
```

and

```
> R.version.string                                  
[1] "R version 3.5.0 (2018-04-23)"                  
> digest("1 2 3 4 5")                               
[1] "46250feb04b8575bf41b61fa7e4b66c4"              
>  
```

and

```
> R.version.string    
[1] "R version 3.3.3 (2017-03-06)"
> digest("1 2 3 4 5")       
[1] "46250feb04b8575bf41b61fa7e4b66c4"
> 
```

Seems to me that the `skip` argument deals with this.

**Comment by eddelbuettel** [comment]
`serialize()` is a base R function I have no control over. `digest()` is what I provide, and it feeds off `serialize()` but as far as I can tell the hand-holding over versions is taken care of for the user of `digest()`.

**Comment by eddelbuettel** [comment]
But you are probably entirely correct on  the sha1 test as

```
if (getRversion() < "3.5.0") {
    stopifnot(
        identical(
            sha1(serialize("e13485e1b995f3e36d43674dcbfedea08ce237bc", NULL)),
            "93ab6a61f1a2ad50d4bf58396dc38cd3821b2eaf"
        )
    )
}
```

works just with `serialize()` and `digest(..., skip="auto")` hence running into this issue.  I'll follow up with the author of that (extensive) sha1 contribution.

**Comment by eddelbuettel** [comment]
@ThierryO Please see above about what @radfordneal pointed out w.r.t. to `serialize()`.  We may have to alter that one test to be less version-dependent here.  Turns out as well that it is the only call to `serialize()` in the tests directory:

```sh
edd@rob:~/git/digest/tests(master)$ grep serialize sha1Test.R 
            sha1(serialize("e13485e1b995f3e36d43674dcbfedea08ce237bc", NULL)),
edd@rob:~/git/digest/tests(master)$ grep serialize *R 
digestTest.R:    md5 <- digest(md5Input[i], serialize=FALSE)
digestTest.R:    md5 <- digest(md5Input[i], serialize=FALSE, raw=TRUE)
digestTest.R:    sha1 <- digest(sha1Input[i], algo="sha1", serialize=FALSE)
digestTest.R:    sha1 <- digest(sha1Input[i], algo="sha1", serialize=FALSE, raw=TRUE)
digestTest.R:    sha512 <- digest(sha512Input[i], algo="sha512", serialize=FALSE)
digestTest.R:    sha512 <- digest(sha512Input[i], algo="sha512", serialize=FALSE, raw=TRUE)
digestTest.R:    crc32 <- digest(crc32Input[i], algo="crc32", serialize=FALSE)
digestTest.R:sha1 <- digest("abc", algo="sha1", serialize=FALSE)
digestTest.R:    xxhash32 <- digest(xxhash32Input[i], algo="xxhash32", serialize=FALSE)
digestTest.R:    xxhash64 <- digest(xxhash64Input[i], algo="xxhash64", serialize=FALSE)
digestTest.R:    murmur32 <- digest(murmur32Input[i], algo="murmur32", serialize=FALSE)
digestTest.R:    h1 <- digest(x    , length=18000, algo=alg, serialize=FALSE)
digestTest.R:    h2 <- digest(fname, length=18000, algo=alg, serialize=FALSE, file=TRUE)
digestTest.R:    h3 <- digest(substr(x,1,18000)  , algo=alg, serialize=FALSE)
digestTest.R:    h4 <- digest(x    , algo=alg, serialize=FALSE)
digestTest.R:    h5 <- digest(fname, algo=alg, serialize=FALSE, file=TRUE)
digestTest.R:    h6 <- digest(xskip, algo=alg, serialize=FALSE)
digestTest.R:    h7 <- digest(fname, algo=alg, serialize=FALSE, skip=20, file=TRUE)
sha1Test.R:            sha1(serialize("e13485e1b995f3e36d43674dcbfedea08ce237bc", NULL)),
edd@rob:~/git/digest/tests(master)$
```

**Comment by ThierryO** [comment]
The problem seems to be bigger than just that test. If the output of `serialize()` depends on the R version, then the output of `sha1()` will depend on it too at it calls `digest()` with it defaults, which have `serialize = TRUE`. The ultimate goal of `sha1()` is to get stable hashes which are independent of OS and R version.

**Comment by eddelbuettel** [comment]
It's been years since I looked at this in detail but the rest of digest seemingly copes fine with this via `skip="auto"`.  We may need to do something similar here then.

I have reasonably easy access to a few R builds via the `r-base` container in Docker (ie the "official" R container) which is versioned (and built via our Rocker r-base container).

**Comment by ThierryO** [comment]
Are you referring to https://hub.docker.com/r/library/r-base/tags/? I have some basic knowledge of Docker. I'll test it against several for these containers.

**Comment by ThierryO** [comment]
I had a look at it. Below the things that I ran to investigate it. All `sha1` hashes were stable. The test with `serialize` fails because the output depends on the R version (as @radfordneal mentioned).

I see two options: a) remove the `sha1` test on `serialize`. b) test if `sha1(serialize(x))` equals the equivalent`digest(serialize(x))`. Is there any added value in option b?

    docker run --rm -it r-base:3.5.0 /bin/bash
    docker run --rm -it r-base:3.4.4 /bin/bash
    docker run --rm -it r-base:3.4.0 /bin/bash
    docker run --rm -it r-base:3.3.3 /bin/bash
    
    apt-get update
    apt-get install -y --no-install-recommends git
    
    git clone --depth=1 https://github.com/thierryo/digest
    R CMD INSTALL digest
    Rscript 'digest/tests/sha1Test.R'
    Rscript -e 'digest::sha1(serialize("e13485e1b995f3e36d43674dcbfedea08ce237bc", NULL))'
    Rscript -e 'serialize("e13485e1b995f3e36d43674dcbfedea08ce237bc", NULL)'

**Comment by eddelbuettel** [comment]
I think a) is fine. There are ample other tests, and one based on `serialiaze()` is simply not applicable as @radfordneal pointed out.  I can just do that here directly, no need for a PR.  But if you want to send one, that would be fine too.

Thanks for the quick check!

**Comment by eddelbuettel** [comment]
Now committed as 03e383203a3938f28245b9b524142c39244faedd.

**Comment by eddelbuettel** [comment]
So closing this now as I forget the tag in the commit.
