### ISSUE TITLE
nchar(digest::digest(51L, algo = "crc32")) == 7 - not 8

### ISSUE THREAD

**Issue by HenrikBengtsson** [eddelbuettel/digest#84]
`?digest` says:
> Value
> The `digest` function **returns a character string of a fixed length** containing the requested digest of the supplied R object. This string is of length 32 for MD5; of length 40 for SHA-1; **of length 8 for CRC32 a string**; of length 8 for for xxhash32; of length 16 for xxhash64; and of length 8 for murmur32.

However, it looks like zero-padding is missing, e.g.
```r
> x <- digest::digest(51L, algo = "crc32")
> x
[1] "82a699e"
> nchar(x)
[1] 7
```

```r
> sessionInfo()
R version 3.5.0 (2018-04-23)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.4 LTS

Matrix products: default
BLAS: /usr/lib/atlas-base/atlas/libblas.so.3.0
LAPACK: /usr/lib/atlas-base/atlas/liblapack.so.3.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.5.0 digest_0.6.15 
```

**Comment by eddelbuettel** [comment]
Hmpf.

Got a suggested patch, by chance?

**Comment by eddelbuettel** [comment]
We could also simply bring the documentation in line with the behaviour as the other counts are as expected -- so we just say crc32 returns something of length seven.

**Comment by HenrikBengtsson** [comment]
If it's due to lack of zero-padding (think `%x` vs `%08x`), which looks to be the case, e.g.
```r
> digest::digest(0L, algo = "crc32")
[1] "b7fa0888"
> digest::digest(51L, algo = "crc32")
[1] "82a699e"
> digest::digest(126L, algo = "crc32")
[1] "4754b3"
> digest::digest(8480L, algo = "crc32")
[1] "b3da3"
> digest::digest(60929L, algo = "crc32")
[1] "e67c"
> digest::digest(180832L, algo = "crc32")
[1] "872"
```
then there will be crc32 code ranging from `00000000`, `00000001`, ..., `ffffffff`, and if zeroS are drop from the front, you'll have `nchar(x)` in [0,8].


Also, it does _not_ seem to be a problem across the board of `algo`:s, e.g.
```r
> digest::digest(11L, algo = "murmur32")
[1] "08bd74cd"
> digest::digest(5L, algo = "xxhash32")
[1] "0ded8a3e"
```

**Comment by eddelbuettel** [comment]
Nice catch. The actual format in two places is 

```c
        sprintf(output, "%2.2x", (unsigned int) val);
```

A naive trial to prefix zero ran afoul of the compiler.  Maybe use a temp buffer first and the sprintf again?

**Comment by eddelbuettel** [comment]
A simple `%08x` does it, and we use it in other places too:

```r
R> library(digest)
R> digest::digest(0L, algo = "crc32")
[1] "b7fa0888"
R> digest::digest(51L, algo = "crc32")
[1] "082a699e"
R> digest::digest(126L, algo = "crc32")
[1] "004754b3"
R> digest::digest(8480L, algo = "crc32")
[1] "000b3da3"
R> digest::digest(60929L, algo = "crc32")
[1] "0000e67c"
R> digest::digest(180832L, algo = "crc32")
[1] "00000872"
R> 
```

**Comment by eddelbuettel** [comment]
Pushed now in [this new branch](https://github.com/eddelbuettel/digest/tree/bugfix/crc_format).

**Comment by HenrikBengtsson** [comment]
Great. So, the remaining question is if this should just be merged as is and hope it will not break too much for anyone using `algo = "crc32"`.  I tend to be overly conservative and provide a migration path, e.g. internal `getOptions(digest.crc32.noleadingzeros = FALSE)` and give a "deprecated" warning and then a "defunct" error in a later release.

**Comment by eddelbuettel** [comment]
I have done that too but here is a) only affects a subset of values and b) a subset of users as I do not think anybody uses crc32.  It was already old (but common / known) when I added it right at the start.

For `md5sum` or `sha1` I'd agree, here it seems overkill.  Also, we have to get down to the C level so it would cost us a new argument.  Is that really worth it?

**Comment by HenrikBengtsson** [comment]
The probability for an 8-hexadecimal crc32 checksum string to have a leading zero is 1/(16-1) = 6.7% (I think).  That is, whoever uses `algo = "crc32"` will most likely be affected by this change.  Whether the change is critical for those users or not is a different question.

For backward compatibility, to get the no-leading-zeros version, a user/devel could always use:
```r
crc32_old <- function(x) sub("^0+", "", digest(x, algo = "crc32"))
```

Yeah, maybe it's not worth all the efforts. It's a bug that gets fixed after all.

**Comment by eddelbuettel** [comment]
The `sub()` idea is good. I think I will offer an `option()` to enable that.  That way we have the best of all worlds.

**Comment by eddelbuettel** [comment]
Done:

```r
R> digest::digest(60929L, algo="crc32")
[1] "0000e67c"
R> options("digestOldCRC32Format"=TRUE)
R> digest::digest(60929L, algo="crc32")
[1] "e67c"
R>
```

This need to add a line to the help page, and add tests for both cases.

**Comment by AlexHNova** [comment]
Wat van data frames vs. gewone character vectors?

**Comment by eddelbuettel** [comment]
Please open a new issue if you have a new question.  And, if you could, write in English please.
