### ISSUE TITLE
Different values compared to OpenSSL

### ISSUE THREAD

**Issue by S-UP** [eddelbuettel/digest#87]
Hi,

I was using your package for internal purposes often. It all worked reliable and stable.

By accident, I discovered that OpenSSL gives quite different values for e.g. sha-1 or md5.

It would be great to add a section in the README to point out why this is. I was not aware and had issues merging sha-1 encoded fields with a 3rd party solution. OpenSSL gives the 'correct' hashes.

Many thanks for the clarification!

**Comment by eddelbuettel** [comment]
You may be confused over the additional header R adds for itself which _you can suppress_.  Just look at the top of the examples:

```r
# Examples:

     ## Standard RFC 1321 test vectors
     md5Input <-
       c("",
         "a",
         "abc",
         "message digest",
         "abcdefghijklmnopqrstuvwxyz",
         "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789",
         paste("12345678901234567890123456789012345678901234567890123456789012",
               "345678901234567890", sep=""))
     md5Output <-
       c("d41d8cd98f00b204e9800998ecf8427e",
         "0cc175b9c0f1b6a831c399e269772661",
         "900150983cd24fb0d6963f7d28e17f72",
         "f96b697d7cb7938d525a2f31aaf161d0",
         "c3fcd3d76192e4007dfb496cca67e13b",
         "d174ab98d277d9f5a5611c2c9f419d9f",
         "57edf4a22be3c955ac49da2e2107b67a")
     
     for (i in seq(along=md5Input)) {
       md5 <- digest(md5Input[i], serialize=FALSE)
       stopifnot(identical(md5, md5Output[i]))
     }
     
     sha1Input <-
       c("abc", "abcdbcdecdefdefgefghfghighijhijkijkljklmklmnlmnomnopnopq")
     sha1Output <- 
       c("a9993e364706816aba3e25717850c26c9cd0d89d",
         "84983e441c3bd26ebaae4aa1f95129e5e54670f1")
     
     for (i in seq(along=sha1Input)) {
       sha1 <- digest(sha1Input[i], algo="sha1", serialize=FALSE)
       stopifnot(identical(sha1, sha1Output[i]))
     }
```

**Comment by eddelbuettel** [comment]
I just poked at the `openssl` command-line tool, I also see a difference.  But if you look at the [RFC](https://www.ietf.org/rfc/rfc1321.txt) I quote you see

```A.5 Test suite

   The MD5 test suite (driver option "-x") should print the following
   results:

MD5 test suite:
MD5 ("") = d41d8cd98f00b204e9800998ecf8427e
MD5 ("a") = 0cc175b9c0f1b6a831c399e269772661
MD5 ("abc") = 900150983cd24fb0d6963f7d28e17f72
MD5 ("message digest") = f96b697d7cb7938d525a2f31aaf161d0
MD5 ("abcdefghijklmnopqrstuvwxyz") = c3fcd3d76192e4007dfb496cca67e13b
MD5 ("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789") =
d174ab98d277d9f5a5611c2c9f419d9f
MD5 ("123456789012345678901234567890123456789012345678901234567890123456
78901234567890") = 57edf4a22be3c955ac49da2e2107b67a
```

you see what I quoted above.  It's been 15 years since I wrote this but I am reasonably certain that I also got the sha1 reference input from a similar source.

**Comment by eddelbuettel** [comment]
For sha1 it is from [its RFC](https://tools.ietf.org/html/rfc3174#section-7.3)

So if openssl is different, methinks you need to look into its side.  It may also just be a usage thing.

**Comment by S-UP** [comment]
Many thanks for your quick reply!

I see that it boils down to the option 'serialize'. If set to FALSE then I get the same values as with the openssl package (or http://www.sha1-online.com/).

Reading the help file of 'digest', I do not quite understand the use case for the option 'serialize'.  Might be helpful to specify more clearly what it is good for. Maybe, it would make sense to change the default so that results are more consistent with other packages/approaches?

**Comment by eddelbuettel** [comment]
The context is use for R, where data is serialized (ie "put in byte form so that it can be sent over the wire or to disk and reconstructed on the other side / later).  `digest()` in its default mode is for just these serialized objects and NOT for reimplementing sha-1 et al.  But we because we have these algos, and it is good to be trustworthy we offer it.

**Comment by eddelbuettel** [comment]
PS And when using R's serialization one needs to add a little bit of a versioning header which is why the result is different for a given input (as it becomes input+header).  So to compare to reference sources, you need `serialize=FALSE`.  Hope this helps.

**Comment by S-UP** [comment]
Thanks for the clarification. Makes sense!
