### ISSUE TITLE
Cannot open input file when filename contains umlaut and file = TRUE

### ISSUE THREAD

**Issue by jRafi** [eddelbuettel/digest#89]
Consider two files which has the same contents, only differing by filename:

```
> dir("data")
[1] "Gavleborg.txt" "Gävleborg.txt"
```

digest::digest works on the file without the "ä".
```
> digest(file.path("data", "Gavleborg.txt"), algo = "md5", file = TRUE)
[1] "85d6d41527468fd765392c6284661e62"
```

But throws an error when used on the file with the "ä", even when replacing ä with \u00E4. Note that the error message contains the correct character, but not the line after the colon.
```
> digest(file.path("data", "Gävleborg.txt"), file = TRUE)
Error in digest(file.path("data", "Gävleborg.txt"), file = TRUE) : 
  Cannot open input file: data/GÃ¤vleborg.txt

> digest(file.path("data", "G\u00E4vleborg.txt"), file = TRUE)
Error in digest(file.path("data", "Gävleborg.txt"), file = TRUE) : 
  Cannot open input file: data/GÃ¤vleborg.txt
```

However, it works when the "file"-argument is removed
```
> digest("data/Gävleborg.txt")
[1] "a8c6abd369f1b7e60c10fd35df55b123"
```

The function is passed with file = TRUE when I deploy a Shiny app to shinyapps.io, so I'm not sure whether this should be considered a bug within the shiny deployment context instead.

**Comment by eddelbuettel** [comment]
Is this Windows-specific?

```sh
edd@rob:~$ cd /tmp
edd@rob:/tmp$ mkdir digest_issue89
edd@rob:/tmp$ cd digest_issue89/
edd@rob:/tmp/digest_issue89$ echo one > gavleborg.txt
edd@rob:/tmp/digest_issue89$ echo two > "Gävleborg.txt"
edd@rob:/tmp/digest_issue89$ Rscript -e 'print(digest::digest("gavleborg.txt"), algo="md5", file="TRUE")'
[1] "0d512e2e80a8c305864537d571f1831a"
edd@rob:/tmp/digest_issue89$ Rscript -e 'print(digest::digest("Gävleborg.txt"), algo="md5", file="TRUE")'
[1] "543e0f885aa2d1dc6d03997d4246742a"
edd@rob:/tmp/digest_issue89$
```

Works here...

**Comment by jRafi** [comment]
Command line on windows:

```
C:\...\digest> echo one > gavleborg.txt
C:\...\digest> echo two > "Gävleborg.txt"

C:\...\digest> Rscript.exe -e "digest::digest('gavleborg.txt', algo='md5', file = TRUE)"
[1] "8d8e662171057e9ab2495bc8f7a67719"

C:\...\digest> Rscript.exe -e "digest::digest('Gävleborg.txt', algo='md5', file = TRUE)"
Error in digest::digest("Gävleborg.txt", algo = "md5", file = TRUE) :
  Cannot open input file: GÃ¤vleborg.txt
Execution halted

**Comment by eddelbuettel** [comment]
I presume there is a windows fix to declare encodings and alike.  But as I work neither on Windows nor with files with utf-8 characters I cannot help you.  Can you peruse the general Windows help for files with 'non-standard' characters?   The digest package only use library functions...

**Comment by jRafi** [comment]
Thanks for investigating! Using the above commands in a MacOS terminal worked. I'll continue working on a Mac as I'd rather not spend time in the world of character encodings.

**Comment by eddelbuettel** [comment]
Appreciate your understanding.  I _think_ all this is fixable, it may just be a matter of encodings, but I also share your general disdain of having to do this.  And "that one OS" seems to be more difficult than others here...
