### ISSUE TITLE
Problem with Shiny Server

### ISSUE THREAD

**Issue by RdeBiotec** [eddelbuettel/digest#96]
Hi everyone,

I am trying to run shiny-server. However, I am having an issue when deploying the apps (they don't deploy). In my log files it only says:

`Error: package ‘digest’ was installed by an R version with different internals; it needs to be reinstalled for use with this R version
Execution halted`

I am working with Shiny Server v1.5.9.923, Node.js v8.11.3, R version 3.5.3 (2019-03-11), Platform: x86_64-pc-linux-gnu (64-bit), Running under: Ubuntu 18.04.2 LTS.

I have tried installing and reinstalling digest (along with every other library and Shiny-Server), from CRAN and from here. Nothing changed. I guess the issue is because of the R version, too new? In that case, will you update soon the digest version or shall I downgrade?

Thanks a lot and apologies for bothering you :)

**Comment by eddelbuettel** [comment]
>  I have tried installing and reinstalling digest 

Exactly what did you do?  Are you aware that you may have the _binary_ package `r-cran-digest` from Ubuntu installed?

In short, do (preferably as the user running shiny, you can use `root` to become that user)

```r
IP <- installed.packages()
IP[ which(IP[,1]=="digest"), ,drop=FALSE]
```

which will show you the details and tell you where your old install came from.  If all else fails seek local help.

There is no issue whatsoever with `digest` so I am closing this here.

**Comment by RdeBiotec** [comment]
You are absolutely right. Thank you very much for pointing me in the right direction (and sorry for bothering you without reason!)

**Comment by eddelbuettel** [comment]
No worries, just wanted to make sure we're on the same page.   Shiny can be hard to debug, and admin'ing R on Linux can be intimidating too.  I remain a firm believer that it _is_ the single best platform but you have to pay attention.  

Also maybe lurk on the r-sig-debian list to learn.   The problem of "R version with different internals" came up after both R 3.4.0 and R 3.5.0 so there are a number of tutorials out there.  Good luck -- and if you're stuck post to r-sig-debian (which also covers Ubuntu).  Note that you _must be_ subscribed to post,
